

	class OFPAddons1DataGlass
	{
		textures[]=
		{	
			"Mi2NO\Rear_X_light.pac",
			"Mi2NO\glow.paa",
			"Mi2NO\glass10.paa",
			"Mi2NO\glass0.paa",
			"Mi2NO\Fr_lght.pac",
			"Mi2NO\button.paa",
			
			"Baracken\glass.paa",
			
			"ags_inds\hang_okna.paa",
			"ags_inds\window_4.pac",
			"ags_inds\light1.pac",
			
			"JOF_Objects1\glass.paa",
			
			"ags_port\glass.paa",
			
			"Apac\apach_in_skla.paa",
			
			"BAS_O\_Tbase\Baswindow.paa",

			"c8x_russ\cob_lens.paa",
			"c8x_usmc\rflxlens.paa",
			"c8x_usmc\rflxlens.pac",

			"CBT_Brad\co\sklo.paa",

			"CSLA_arm\skot\svetlom.pac",
			"CSLA_arm\skot\svetla.paa",
			"CSLA_arm\t72\optick.paa",

			"mi2no\glass1.paa",
			"mi2no\glass10.paa",

			"sig_t72B\light90.paa",	
		};
		material="#OFPglass";
	};
	
	class OFPAddons1DataMetalVeh
	{
		textures[]=
		{	
			"Mi2NO\ZVEZDA.PAA",
			"Mi2NO\weapon_side.pac",
			"Mi2NO\weapon_pylon.pac",
			"Mi2NO\weapon_front.pac",
			"Mi2NO\Vint_rear.pac",
			"Mi2NO\Vint_front.pac",
			"Mi2NO\velka_vrtule_blu.paa",
			"Mi2NO\velka_vrtule.paa",
			"Mi2NO\Side2.pac",
			"Mi2NO\Side.pac",
			"Mi2NO\rXpivot.pac",
			"Mi2NO\Rear_wings.pac",
			"Mi2NO\Rear_d.pac",
			"Mi2NO\Rear_body.pac",
			"Mi2NO\NURS_back.pac",
			"Mi2NO\mala_vrtule_blur.paa",
			"Mi2NO\mala_vrtule.paa",
			"Mi2NO\Jet_intake_1.pac",
			"Mi2NO\hor_line.paa",
			"Mi2NO\Front_e.pac",
			"Mi2NO\Front_dr.pac",
			"Mi2NO\frgear.pac",
			"Mi2NO\empty.pac",
			"Mi2NO\Drkgry.pac",
			"Mi2NO\details.pac",
			"Mi2NO\Chrome.pac",
			"Mi2NO\Body_front.pac",
			"Mi2NO\Blue.pac",
			"Mi2NO\black.pac",
			"BAS_O\_tobj\bas_i1car2.pac",
			"BAS_O\_tobj\bas_i1car1.pac",
			
			"BAS_O\_tx\cy_sidetga.paa",
			"BAS_O\_tx\cy_roof.pac",
			"BAS_O\_tx\cy_hood.pac",
			"BAS_O\_tx\cy_front.pac",
			"BAS_O\_tx\cy_boot.pac",
			"BAS_O\_tx\cy_back.pac",
			"BAS_O\_tx\cr_side2tga.paa",
			"BAS_O\_tx\cr_roof.pac",
			"BAS_O\_tx\cr_hood.pac",
			"BAS_O\_tx\cr_front.pac",
			"BAS_O\_tx\cr_boot.pac",
			"BAS_O\_tx\cr_back.pac",
			"BAS_O\_tx\cg_side.paa",
			"BAS_O\_tx\cg_side.paa",
			"BAS_O\_tx\cg_roof.pac",
			"BAS_O\_tx\cg_hood.pac",
			"BAS_O\_tx\cg_front.pac",
			"BAS_O\_tx\cg_boot.pac",
			"BAS_O\_tx\cg_back.pac",
			"BAS_O\_tx\cb_side3.paa",
			"BAS_O\_tx\cb_side2.pac",
			"BAS_O\_tx\cb_roof.pac",
			"BAS_O\_tx\cb_hood.pac",
			"BAS_O\_tx\cb_front.pac",
			"BAS_O\_tx\cb_boot.pac",
			"BAS_O\_tx\cb_back.pac",
			
			"COC_Arty\M109\body.paa",
			"COC_Arty\M109\turret1.paa",
			"COC_Arty\M109\turret.paa",
			"COC_Arty\M109\vloerpl.paa",		
			"COC_Arty\M109\black.paa",
			"COC_Arty\M109\body.pac",	
			"COC_Arty\M109\grate.pac",
			"COC_Arty\M109\grate.pac",
			"COC_Arty\M109\palside.pac",
			"COC_Arty\M109\turret1.pac",
			"COC_Arty\M109\turret.pac",	
			"COC_Arty\M109\wheel.pac",
			"COC_Arty\M109\wheel2.pac",
			"COC_Arty\M109\wheel4.pac",	
		};
		material="#OFPmetalVeh";
	};

	class OFPAddons1vehinterior
	{
		textures[]=
		{	
			"Mi2NO\pilot_sidene.pac",
			"Mi2NO\pas_sidene.pac",
			"Mi2NO\panel1hi_p.paa",
			"Mi2NO\panel1hi.paa",
			"Mi2NO\panel1.pac",
			"Mi2NO\panel_right.paa",
			"Mi2NO\panel_left.paa",
			"Mi2NO\p2.pac",
			"Mi2NO\p1.pac",
			"Mi2NO\interrior_steniz.pac",
			"Mi2NO\interrior_steni.pac",
			"Mi2NO\interrior_potolo.pac",
			"Mi2NO\interrior_front.pac",
			"Mi2NO\interrior_fd.pac",
			"Mi2NO\interrior_bd.pac",
			"Mi2NO\interfouter.pac",
			"Mi2NO\inter_tool9.pac",
			"Mi2NO\inter_tool8.pac",
			"Mi2NO\inter_tool7.pac",
			"Mi2NO\inter_tool6.pac",
			"Mi2NO\inter_tool5.pac",
			"Mi2NO\inter_tool4.pac",
			"Mi2NO\inter_tool3.pac",
			"Mi2NO\inter_tool2.pac",
			"Mi2NO\inter_tool1.pac",
			"Mi2NO\antifire.pac",
			"Mi2NO\antifire.pac",
			"Mi2NO\airhorizont.pac",
			
			"BAS_O\_tobj\bas_i1car3.paa",
			
			"BAS_O\_tx\cy_intgac.pac",
			"BAS_O\_tx\cy_intgaa.paa",
			"BAS_O\_tx\cy_in.pac",
			"BAS_O\_tx\cr_intga.paa",
			"BAS_O\_tx\cr_in.pac",
			"BAS_O\_tx\cg_sidel.paa",
			"BAS_O\_tx\cg_in.pac",
			"BAS_O\_tx\cb_in.pac"
		};
		material="#OFPvehinterior";
	};

	class OFPAddons1DataMetal
	{
		textures[]=
		{		
			"Mi2NO\C\Jet_inta3M.pac",
			
			"AEF_Reallights\lamppole.paa",

			"seb_ilo\h\she - roof2.pac",
			"seb_ilo\h\sh - side2.pac",
			"seb_ilo\h\sh - roof2.pac",
			"seb_ilo\h\sh - front2.pac",
			"seb_ilo\h\sh - back2.pac",
			
			"BAS_O\b_texm\bal2.paa",
			"BAS_O\b_texm\bal1.paa",
			"BAS_O\b_texm\aco1.paa",
			
			"BAS_O\o_ags\metflr1b.pac",
			"BAS_O\o_ags\metal_r.pac",
			"BAS_O\o_ags\metal_brsd.pac",
			"BAS_O\o_ags\light1.pac",
			"BAS_O\o_ags\fire_hose1.pac",
			"BAS_O\o_ags\door_g.pac",
			"BAS_O\o_ags\ce_galv.pac",
			
			"BAS_O\t\metal1.paa",
			"BAS_O\t\hocorruiron4.paa",
			"BAS_O\t\hocorruiron2.paa",
			
			"BAS_O\_c\she - roof3.pac",
			"BAS_O\_c\she - roof2.pac",
			"BAS_O\_c\she - fr2.pac",
			"BAS_O\_c\shanty - roofb.pac",
			"BAS_O\_c\shanty - roof.pac",
			"BAS_O\_c\sh - side2.pac",
			"BAS_O\_c\sh - roof2.pac",
			"BAS_O\_c\sh - front2.pac",
			"BAS_O\_c\sh - back2.pac",
			"BAS_O\_c\int - side2.pac",
			"BAS_O\_c\int - fr2.pac",
			"BAS_O\_c\int - back2.pac",
			
			"BAS_O\_infra\slumlodtop.paa",
			"BAS_O\_infra\slumlodside.paa",
			
			"BAS_O\_slum\tr_09.pac",
			"BAS_O\_slum\tr_08.pac",
			"BAS_O\_slum\tr_07.pac",
			"BAS_O\_slum\tr_06.pac",
			"BAS_O\_slum\tr_05.pac",
			"BAS_O\_slum\tr_04.pac",
			"BAS_O\_slum\tr_03.pac",
			"BAS_O\_slum\tr_02.pac",
			"BAS_O\_slum\tr_011.pac",
			"BAS_O\_slum\tr_01.pac",
			"BAS_O\_slum\t_04f.pac",
			"BAS_O\_slum\t_03f.pac",
			"BAS_O\_slum\t_02f.pac",
			"BAS_O\_slum\t_02.pac",
			"BAS_O\_slum\c_08s2.pac",
			"BAS_O\_slum\c_08s.pac",
			"BAS_O\_slum\c_08g.pac",
			"BAS_O\_slum\c_08.pac",
			
			"BAS_O\_t\bastinwall.pac",
			"BAS_O\_t\barrelfire.paa",
			"BAS_O\_t\barrel1t.pac",
			"BAS_O\_t\barrel1.pac",
			
			"BAS_O\_tbase\tins3.pac",
			"BAS_O\_tbase\tins2.pac",
			"BAS_O\_tbase\rebfuel.paa",
			"BAS_O\_tbase\front2.pac",
			"BAS_O\_tbase\brace1.paa",
			"BAS_O\_tbase\bastin1.pac",
			
			"BAS_O\_tmisc\vanimo.paa",
			"BAS_O\_tmisc\lst.pac",
			"BAS_O\_tmisc\lorengau.paa",
			"BAS_O\_tmisc\balimo.paa",
			
			"BAS_O\_tx\autzst_tc.pac",
			"BAS_O\_tx\autzst_strch.pac",
			
			"afganO\rouille2.pac",
			"afganO\rouille1.pac",
			
			"Baracken\gitter2.pac",
			"Baracken\gitter1.pac",
			"Baracken\blech4.paa",
			"Baracken\blech3.paa",
			"Baracken\blech2.paa",
			"Baracken\airport.pac",
			"Baracken\5well.pac",
			"Baracken\4well.pac",
			"Baracken\3well.pac",
			"Baracken\2well.pac",
			"Baracken\1well.pac",
			
			"ags_inds\wall_ym2.pac",
			"ags_inds\to1_vrata.pac",
			"ags_inds\steelframe.paa",
			"ags_inds\sign_nofoto.pac",
			"ags_inds\mtl_cr_red2.pac",
			"ags_inds\metal_ch2.pac",
			"ags_inds\metal_ch.pac",
			"ags_inds\m02_pipes.pac",
			"ags_inds\htank_side.pac",
			"ags_inds\hangarw1b.pac",
			"ags_inds\hang_zabradli.paa",
			"ags_inds\doravnik.pac",
			"ags_inds\d02_silob.pac",
			"ags_inds\d02_silo.pac",
			"ags_inds\d02_rustedpipes.pac",
			"ags_inds\airvent1.pac",
			"ags_inds\tankside2.pac",
			"ags_inds\tankside.pac",
			"ags_inds\shiny tank.pac",
			"ags_inds\railing_s.pac",
			"ags_inds\railing.pac",
			"ags_inds\pressurised3.pac",
			"ags_inds\gas decanter.pac",
			"ags_inds\mtl_cr_ye.pac",
			"ags_inds\metflr1b.pac",
			"ags_inds\metal_trim1.pac",
			"ags_inds\metal_r.pac",
			"ags_inds\metal_brsd.pac",
			"ags_inds\ladder.paa",
			"ags_inds\girder2c.paa",
			"ags_inds\fire_hose1.pac",
			"ags_inds\door_garage2.pac",
			"ags_inds\door_g.pac",
			"ags_inds\ce_galv.pac",
			
			"JOF_Objects1\mineltd.pac",
			"JOF_Objects1\claymorefront.pac",
			"JOF_Objects1\claymoreback.pac",
			"JOF_Objects1\air_control.pac",
			
			"ags_port\yellow_side.pac",
			"ags_port\yellow_door.pac",
			"ags_port\red_side.pac",
			"ags_port\red_side.pac",
			"ags_port\red_door.pac",
			"ags_port\mtl_green.pac",
			"ags_port\mtl_flr.pac",
			"ags_port\mtl_cr_ye.pac",
			"ags_port\mtl_cr_red.pac",
			"ags_port\mtl_cr_ee.pac",
			"ags_port\metal_r.pac",
			"ags_port\metal_cable.pac",
			"ags_port\green_side.pac",
			"ags_port\green_door.pac",
			"ags_port\grating.pac",
			"ags_port\controls.pac",
			"ags_port\ce_galv.pac",
			"ags_port\blue_side.pac",
			"ags_port\blue_door.pac",

			"BAS_O\_c\sh - back2.pac",
			"BAS_O\_c\sh - back3.pac",
			"BAS_O\_c\sh - front2.pac",
			"BAS_O\_c\sh - front3.pac",
			"BAS_O\_c\sh - roof2.pac",
			"BAS_O\_c\sh - roof3.pac",
			"BAS_O\_c\sh - side2.pac",
			"BAS_O\_c\sh - side3.pac",
			"BAS_O\_c\shanty - roof.pac",
			"BAS_O\_c\she - fr2.pac",
			"BAS_O\_c\she - fr3.pac",
			"BAS_O\_c\she - roof2.pac",	
			"BAS_O\_c\she - roof3.pac",
			
			"BAS_O\_infra\slumlodtop.paa",

			"BAS_O\_slum\c_08.pac",
			"BAS_O\_slum\c_08g.pac",
			"BAS_O\_slum\c_08s2.pac",
			"BAS_O\_slum\c_08s.pac",
			"BAS_O\_slum\t_02f.pac",
			"BAS_O\_slum\t_03f.pac",
			"BAS_O\_slum\tr_01.pac",
			"BAS_O\_slum\tr_02.pac",
			"BAS_O\_slum\tr_03.pac",
			"BAS_O\_slum\tr_04.pac",
			"BAS_O\_slum\tr_05.pac",
			"BAS_O\_slum\tr_06.pac",
			"BAS_O\_slum\tr_07.pac",
			"BAS_O\_slum\tr_08.pac",
			"BAS_O\_slum\tr_09.pac",
			"BAS_O\_slum\tr_011.pac",
		
			"BAS_O\_T\barrel1.pac",
			"BAS_O\_T\barrel1t.pac",
			"BAS_O\_T\barrelfire.pac",

			"BAS_O\_Tbase\bastin1.pac",
			"BAS_O\_Tbase\bastin1.pac",
			"BAS_O\_Tbase\brace1.paa",
			"BAS_O\_Tbase\rebfuel.paa",
			"BAS_O\_Tbase\tins2.pac",
			"BAS_O\_Tbase\tins3.pac",
			
			"BAS_O\_Tmisc\lst.pac",
				
			"BAS_O\_Tobj\bas_icar1.pac",	
			"BAS_O\_Tobj\bas_icar2.pac",

			"BAS_O\_Tx\cb_back.pac",
			"BAS_O\_Tx\cb_boot.pac",
			"BAS_O\_Tx\cb_front.pac",
			"BAS_O\_Tx\cb_hood.pac",
			"BAS_O\_Tx\cb_roof.pac",
			"BAS_O\_Tx\cb_side2.pac",
			"BAS_O\_Tx\cb_side3.paa",	
			"BAS_O\_Tx\cg_back.pac",
			"BAS_O\_Tx\cg_boot.pac",
			"BAS_O\_Tx\cg_front.pac",
			"BAS_O\_Tx\cg_hood.pac",
			"BAS_O\_Tx\cg_roof.pac",
			"BAS_O\_Tx\cg_side.paa",
			"BAS_O\_Tx\cg_sidel.paa",	
			"BAS_O\_Tx\cr_back.pac",
			"BAS_O\_Tx\cr_boot.pac",
			"BAS_O\_Tx\cr_front.pac",
			"BAS_O\_Tx\cr_hood.pac",
			"BAS_O\_Tx\cr_roof.pac",
			"BAS_O\_Tx\cr_side2tga.paa",
			"BAS_O\_Tx\cy_back.pac",
			"BAS_O\_Tx\cy_boot.pac",
			"BAS_O\_Tx\cy_front.pac",
			"BAS_O\_Tx\cy_hood.pac",
			"BAS_O\_Tx\cy_roof.pac",
			"BAS_O\_Tx\cy_sidetga.paa",

			"BAS_O\o_ags\ce_galv.pac",
			"BAS_O\o_ags\door_g.pac",
			"BAS_O\o_ags\metal_brsd.pac",	
			"BAS_O\o_ags\metal_r.pac",
			"BAS_O\o_ags\metflr1b.pac",
			
			"ICP_rfwp\r109_radio\r109.paa"
		};
		material="#OFPmetal";
	};
	
	class OFPAddons1RifleMetal
	{
		textures[]=
		{		
					
			"Mi2NO\at3.pac",
			
			"c8x_russ\1p29.pac",
			"c8x_russ\ak74m.pac",
			"c8x_russ\ak74mgr.pac",
			"c8x_russ\ak74mgs.pac",
			"c8x_russ\aks74u.pac",
			"c8x_russ\cobra.pac",
			"c8x_russ\gp25.pac",
			"c8x_russ\rpk74.pac",
			"c8x_russ\rpk74mb.paa",
			"c8x_russ\rpk74mb.pac",
			"c8x_russ\rpk74ms.paa",
			"c8x_russ\rpk74ms.pac",
			"c8x_russ\rpkmag.pac",
	
			"c8x_usmc\acog.pac",	
			"c8x_usmc\m4.pac",
			"c8x_usmc\m4_sl.paa",
			"c8x_usmc\m4_tr.paa",
			"c8x_usmc\m16.pac",
			"c8x_usmc\m16a2.pac",
			"c8x_usmc\m16a2_hg.pac",
			"c8x_usmc\m16a2low.paa",
			"c8x_usmc\m16a2low.pac",
			"c8x_usmc\m16ac_lo.paa",
			"c8x_usmc\m16ac_lo.pac",	
			"c8x_usmc\m16c_lo.paa",
			"c8x_usmc\m16c_lo.pac",
			"c8x_usmc\m16ga_lo.paa",
			"c8x_usmc\m16ga_lo.pac",
			"c8x_usmc\m16gc_lo.paa",
			"c8x_usmc\m16gc_lo.pac",
			"c8x_usmc\m16gr_lo.paa",
			"c8x_usmc\m16gr_lo.pac",
			"c8x_usmc\m16rx_lo.paa",
			"c8x_usmc\m16rx_lo.pac",
			"c8x_usmc\m145.pac",
			"c8x_usmc\m203.pac",
			"c8x_usmc\m203leaf.pac",
			"c8x_usmc\m249.pac",
			"c8x_usmc\m249acc.pac",
			"c8x_usmc\m249b.paa",
			"c8x_usmc\m249b.pac",
			"c8x_usmc\m249belt.01.paa",
			"c8x_usmc\m249belt.02.paa",
			"c8x_usmc\m249belt.paa",
			"c8x_usmc\m249p_sl.paa",
			"c8x_usmc\m249p_tr.paa",
			"c8x_usmc\m249s.paa",
			"c8x_usmc\m249s.pac",
			"c8x_usmc\m1014.pac",
			"c8x_usmc\reflex.pac",	

			"ICP_rfwp\ak74\ak74_low.paa",
			"ICP_rfwp\ak74\ak74m_lo.paa",
			"ICP_rfwp\ak74\ak74mpl.paa",
			"ICP_rfwp\ak74\ak74msk.paa",
			"ICP_rfwp\ak74\ak74mslo.paa",
			"ICP_rfwp\ak74\ak74pl.paa",
			"ICP_rfwp\ak74\ak74pr.paa",
			"ICP_rfwp\ak74\ak74s_lo.paa",
			"ICP_rfwp\ak74\ak74sciv.paa",
			"ICP_rfwp\ak74\ak74sk.paa",
			"ICP_rfwp\ak74\ak74ssk.paa",
			"ICP_rfwp\ak74\ak74stv.paa",
			"ICP_rfwp\ak74\ak74supl.paa",
			"ICP_rfwp\ak74\ak74sust.paa",
			"ICP_rfwp\ak74\akm47_ma.paa",
			"ICP_rfwp\ak74\akms_pr.paa",
			"ICP_rfwp\ak74\akmsb_lo.paa",
			"ICP_rfwp\ak74\aksu_low.paa",
			"ICP_rfwp\ak74\gp.pac",
			"ICP_rfwp\ak74\gp_lod.paa",
			"ICP_rfwp\ak74\pso1.paa",
			"ICP_rfwp\ak74\pso2.paa",
			"ICP_rfwp\ak74\rpk74ma.paa",
			"ICP_rfwp\ak74\rpk74sk.paa",
			"ICP_rfwp\ak74\rpk_lo.paa",
			"ICP_rfwp\ak74\spus_low.paa",
			"ICP_rfwp\ak74\vss_lo.paa",
			
			"ICP_rfwp\pkm\ak74mpl.paa",
			"ICP_rfwp\pkm\ak74supl.paa",
			"ICP_rfwp\pkm\pk_cin.paa",
			"ICP_rfwp\pkm\pk_len.paa",
			"ICP_rfwp\pkm\pk_low.paa",
			"ICP_rfwp\pkm\pk_sk.paa",
			"ICP_rfwp\pkm\pk_stv.paa",
			"ICP_rfwp\pkm\pkLo_l.paa",
			"ICP_rfwp\pkm\pkLo_s.paa",
			"ICP_rfwp\pkm\pkm_low.paa",
			"ICP_rfwp\pkm\pkm_stv.paa",

			"ICP_rfwp\svd\pso1.paa",
			"ICP_rfwp\svd\pso2.paa",
			"ICP_rfwp\svd\svd_ma.paa",
			"ICP_rfwp\svd\svd_sk.paa",
			"ICP_rfwp\svd\svd_sp.paa",
			"ICP_rfwp\svd\svd_stv.paa",
			"ICP_rfwp\svd\svds_lo.paa",
			"ICP_rfwp\svd\svds_pri.paa",
			"ICP_rfwp\svd\svds_sk.paa",
			"ICP_rfwp\svd\svds_sp.paa",

			"ICP_rfwp\vss\10_mag.paa",
			"ICP_rfwp\vss\20_mag.paa",
			"ICP_rfwp\vss\pso1.paa",
			"ICP_rfwp\vss\pso2.paa",
			"ICP_rfwp\vss\val_lo.paa",
			"ICP_rfwp\vss\val_pri.paa",
			"ICP_rfwp\vss\vss_lo.paa",
			"ICP_rfwp\vss\vss_sk.paa",
			"ICP_rfwp\vss\vss_sp.paa",
			"ICP_rfwp\vss\vss_stv.paa",			

			"kozl\kozlopak.pac",
			
		};
		material="#OFPriflemetal";
	};
	
	class OFPAddons1Buildings
	{
		textures[]=
		{	

			"seb_ilo\ap.paa",
			
			"BAS_O\b_texm\boi7.paa",
			"BAS_O\b_texm\boi4.paa",
			"BAS_O\b_texm\bamb1.paa",
			"BAS_O\b_texm\avia.paa",
			"BAS_O\b_texm\affi1.paa",
			
			"BAS_O\o_ags\top_s.pac",
			"BAS_O\o_ags\door3b.pac",
			"BAS_O\o_ags\concrete3.pac",
			"BAS_O\o_ags\concrete2.pac",
			
			"BAS_O\t\wall2.paa",
			"BAS_O\t\twall2.paa",
			"BAS_O\t\townflat1.paa",
			"BAS_O\t\town4.paa",
			"BAS_O\t\tentwood2.paa",
			"BAS_O\t\tentwood.paa",
			"BAS_O\t\lawoodwall.paa",
			"BAS_O\t\doors.paa",
			"BAS_O\t\bawood3b.paa",
			"BAS_O\t\bawood3.paa",
			"BAS_O\t\bawood2.paa",
			"BAS_O\t\bawood.paa",
			"BAS_O\t\baplex.paa",
			"BAS_O\t\baplas.paa",
			"BAS_O\t\bafloo.paa",
			"BAS_O\t\babast.paa",
			"BAS_O\t\babas2.paa",
			
			"BAS_O\_c\tower.pac",
			"BAS_O\_c\top.pac",
			"BAS_O\_c\stinnerside.pac",
			"BAS_O\_c\st-in-fro-ba.pac",
			"BAS_O\_c\st-food2.pac",
			"BAS_O\_c\stall_bottom.pac",
			"BAS_O\_c\stall - side.pac",
			"BAS_O\_c\stall - leg.pac",
			"BAS_O\_c\stall - front.pac",
			"BAS_O\_c\stall - food.pac",
			"BAS_O\_c\stall - bottom.pac",
			"BAS_O\_c\stall - back.pac",
			"BAS_O\_c\stake.pac",
			"BAS_O\_c\side3.pac",
			"BAS_O\_c\side2.pac",
			"BAS_O\_c\side1.pac",
			"BAS_O\_c\side.pac",
			"BAS_O\_c\side - small2.pac",
			"BAS_O\_c\side - small.pac",
			"BAS_O\_c\side - long2.pac",
			"BAS_O\_c\side - long.pac",
			"BAS_O\_c\she - fr3.pac",
			"BAS_O\_c\shantye - fr.pac",
			"BAS_O\_c\shanty - side.pac",
			"BAS_O\_c\shanty - front.pac",
			"BAS_O\_c\shanty - back.pac",
			"BAS_O\_c\sh - side3.pac",
			"BAS_O\_c\sh - roof3.pac",
			"BAS_O\_c\sh - front3.pac",
			"BAS_O\_c\sh - back3.pac",
			"BAS_O\_c\roof.pac",
			"BAS_O\_c\roof.pac",
			"BAS_O\_c\minwin.pac",
			"BAS_O\_c\minplain.pac",
			"BAS_O\_c\mindo.pac",
			"BAS_O\_c\long-rear.pac",
			"BAS_O\_c\long-front.pac",
			"BAS_O\_c\long-front.pac",
			"BAS_O\_c\interior - fr.pac",
			"BAS_O\_c\int - wall3.pac",
			"BAS_O\_c\int - wall2.pac",
			"BAS_O\_c\int - wall.pac",
			"BAS_O\_c\int - side3.pac",
			"BAS_O\_c\int - side.pac",
			"BAS_O\_c\int - fr3.pac",
			"BAS_O\_c\int - back3.pac",
			"BAS_O\_c\int - back.pac",
			"BAS_O\_c\inner.pac",
			"BAS_O\_c\front.pac",
			"BAS_O\_c\front - small.pac",
			"BAS_O\_c\front - long.pac",
			"BAS_O\_c\btopw.pac",
			"BAS_O\_c\bsidew.pac",
			"BAS_O\_c\bside2.pac",
			"BAS_O\_c\broof.pac",
			"BAS_O\_c\binner.pac",
			"BAS_O\_c\bfront.pac",
			"BAS_O\_c\bbtop.pac",
			"BAS_O\_c\bbside.pac",
			"BAS_O\_c\bback.pac",
			"BAS_O\_c\back.pac",
			"BAS_O\_c\back - small.pac",
			"BAS_O\_c\back - long.pac",
			
			"BAS_O\_slum\w_edge.pac",
			"BAS_O\_slum\t_06f.pac",
			"BAS_O\_slum\t_01f.pac",
			"BAS_O\_slum\t_01.pac",
			"BAS_O\_slum\c_07xx.pac",
			"BAS_O\_slum\c_07x.pac",
			"BAS_O\_slum\c_07.pac",
			"BAS_O\_slum\c_06.pac",
			"BAS_O\_slum\c_05.pac",
			"BAS_O\_slum\c_04.pac",
			"BAS_O\_slum\c_03.pac",
			"BAS_O\_slum\c_02xx.pac",
			"BAS_O\_slum\c_02x.pac",
			"BAS_O\_slum\c_02.pac",
			"BAS_O\_slum\c_01x.pac",
			"BAS_O\_slum\c_01.pac",
			
			"BAS_O\_t\scarab.paa",
			"BAS_O\_t\messl.paa",
			"BAS_O\_t\mess1.paa",
			"BAS_O\_t\bastable1.pac",
			"BAS_O\_t\basGW3.pac",
			"BAS_O\_t\basGW2.pac",
			"BAS_O\_t\basGW1.pac",
			"BAS_O\_t\basfirewood.paa",
			
			"BAS_O\_tbase\wall2.pac",
			"BAS_O\_tbase\twr_wall2.paa",
			"BAS_O\_tbase\twr_wall1.paa",
			"BAS_O\_tbase\term_wall5.paa",
			"BAS_O\_tbase\term_wall4.paa",
			"BAS_O\_tbase\term_wall3.paa",
			"BAS_O\_tbase\term_wall2.paa",
			"BAS_O\_tbase\term_wall1.paa",
			"BAS_O\_tbase\term_countr2.paa",
			"BAS_O\_tbase\term_countr1.paa",
			"BAS_O\_tbase\shop5.paa",
			"BAS_O\_tbase\sbw.paa",
			"BAS_O\_tbase\poster5.paa",
			"BAS_O\_tbase\poster4.paa",
			"BAS_O\_tbase\poster3.paa",
			"BAS_O\_tbase\floor1.paa",
			"BAS_O\_tbase\floor.paa",
			"BAS_O\_tbase\dirty2.paa",
			"BAS_O\_tbase\dirty1.paa",
			"BAS_O\_tbase\ceiling1.paa",
			"BAS_O\_tbase\board7.paa",
			"BAS_O\_tbase\board6.paa",
			"BAS_O\_tbase\board5.paa",
			"BAS_O\_tbase\board4.paa",
			"BAS_O\_tbase\board3.paa",
			"BAS_O\_tbase\board2.paa",
			"BAS_O\_tbase\board1.paa",
			"BAS_O\_tbase\baswoodb.paa",
			"BAS_O\_tbase\basroofb.paa",
			"BAS_O\_tbase\basroofa.pac",
			"BAS_O\_tbase\basroofa.paa",
			"BAS_O\_tbase\bascement.pac",
			"BAS_O\_tbase\basbrick1.paa",
			"BAS_O\_tbase\basbrick1 PALE.paa",
			"BAS_O\_tbase\basbrick1 last.paa",
			"BAS_O\_tbase\basbrick.paa",
			"BAS_O\_tbase\bas_crnr2.paa",
			"BAS_O\_tbase\bas_crnr1.paa",
			
			"BAS_O\_Td\zbor_dum_zdivo.pac",
			"BAS_O\_Td\zbor_dum_total_zdivo.pac",
			"BAS_O\_Td\zbor_dum_total_trame.pac",
			"BAS_O\_Td\zbor_dum_total_strop.pac",
			"BAS_O\_Td\zbor_dum_total_stram.pac",
			"BAS_O\_Td\zbor_dum_total_lod.pac",
			"BAS_O\_Td\zbor_dum_total_in.pac",
			"BAS_O\_Td\zbor_dum_total.pac",
			"BAS_O\_Td\zbor_dum_stena2b.pac",
			"BAS_O\_Td\zbor_dum_stena2.pac",
			"BAS_O\_Td\zbor_dum_stena1b.pac",
			"BAS_O\_Td\zbor_dum_stena1.pac",
			"BAS_O\_Td\zbor_dum_stena_in.pac",
			"BAS_O\_Td\zbor_dum_podlaha.pac",
			"BAS_O\_Td\zbor_dum_meziokn.pac",
			"BAS_O\_Td\zbor_dum_lidicelod.pac",
			"BAS_O\_Td\zb_d_lod.pac",
			"BAS_O\_Td\ruinsjoin.pac",
			"BAS_O\_Td\podlaha_prkna_h.pac",
			
			"BAS_O\_thouse\thatch1.pac",
			"BAS_O\_thouse\hut2.pac",
			"BAS_O\_thouse\hut2.paa",
			"BAS_O\_thouse\hut1i.pac",
			"BAS_O\_thouse\hut1.pac",
			"BAS_O\_thouse\hut1.paa",
			"BAS_O\_thouse\floor.paa",
			
			"BAS_O\_tmisc\poster12.paa",
			"BAS_O\_tmisc\poster08.paa",
			"BAS_O\_tmisc\poster07.paa",
			"BAS_O\_tmisc\poster01.paa",
			"BAS_O\_tmisc\kybl1.pac",
			
			"BAS_O\_twood\woodroof.paa",
			"BAS_O\_twood\woodedge.paa",
			"BAS_O\_twood\wooddock.paa",
			"BAS_O\_twood\wood5.pac",
			"BAS_O\_twood\wood4.pac",
			"BAS_O\_twood\wood3.pac",
			"BAS_O\_twood\roof_lod2.paa",
			"BAS_O\_twood\roof_lod1.paa",
			"BAS_O\_twood\planks2.pac",
			"BAS_O\_twood\planks1.pac",
			"BAS_O\_twood\edge2.pac",
			"BAS_O\_twood\dirty.pac",
			"BAS_O\_twood\dark_lod2.paa",
			"BAS_O\_twood\dark_lod1.paa",
			"BAS_O\_twood\boards.paa",
			"BAS_O\_twood\bas_wp1.paa",
			
			"BAS_O\_tx\bky.pac",
			"BAS_O\_tx\autzst_pr.pac",
			
			"afganO\Ltex\mursable.pac",
			"afganO\Ltex\murpierre.pac",
			"afganO\Ltex\mosqueL.paa",
			"afganO\Ltex\maisonsable.pac",
			"afganO\Ltex\maisonpierrel.pac",
			"afganO\Ltex\maisonpierre.pac",
			"afganO\tex\tissu1.pac",
			"afganO\tex\tis4.pac",
			"afganO\tex\tis3.pac",
			"afganO\tex\tis3.paa",
			"afganO\tex\tapisj.pac",
			"afganO\tex\tapisb.pac",
			"afganO\tex\tapis.pac",
			"afganO\tex\soldeco.pac",
			"afganO\tex\porte.pac",
			"afganO\tex\pierregrises.pac",
			"afganO\tex\murvert.paa",
			"afganO\tex\murterreu.pac",
			"afganO\tex\murterrec.pac",
			"afganO\tex\mursableu.pac",
			"afganO\tex\mursablec.pac",
			"afganO\tex\murpierreu.pac",
			"afganO\tex\murpierrec.pac",
			"afganO\tex\mouch.paa",
			"afganO\tex\motifjaune.pac",
			"afganO\tex\l5mstars.paa",
			"afganO\tex\islam2.paa",
			"afganO\tex\islam.paa",
			"afganO\tex\gravier.paa",
			"afganO\tex\fenridrouge.pac",
			"afganO\tex\fenridrouge.paa",
			"afganO\tex\fenridbleu.pac",
			"afganO\tex\fenridbleu.paa",
			"afganO\tex\farci.pac",
			"afganO\tex\carvt.pac",
			"afganO\tex\carbl.pac",
			"afganO\tex\caravp2c.paa",
			"afganO\tex\calig2.pac",
			"afganO\tex\calig1.pac",
			"afganO\tex\cadre.paa",
			"afganO\tex\algerie.paa",
			"afganO\tex\afgan.pac",
			"afganO\zidka01a.pac",
			"afganO\zidka01.pac",
			"afganO\massoud.paa",
			"afganO\fouintrace.paa",
			"afganO\fouin.paa",
			"afganO\benladen.paa",
			"afganO\afgan.paa",
			
			"Baracken\united.pac",
			"Baracken\tor.pac",
			"Baracken\novofon.pac",
			"Baracken\novofon.paa",
			"Baracken\novel.pac",
			"Baracken\novel.paa",
			"Baracken\nogacola.pac",
			"Baracken\nogacola.paa",
			"Baracken\mine.pac",
			"Baracken\holz7.pac",
			"Baracken\holz6.pac",
			"Baracken\ggg.pac",
			"Baracken\blazena.pac",
			"Baracken\blazena.paa",
			"Baracken\aerolinie.pac",
			
			"ags_inds\wall042.pac",
			"ags_inds\wall010_b.pac",
			"ags_inds\wall010_1.pac",
			"ags_inds\wall_trafo2.pac",
			"ags_inds\wall_trafo.pac",
			"ags_inds\to1_stenalux.paa",
			"ags_inds\to1_stenainter.pac",
			"ags_inds\frontage006.pac",
			"ags_inds\door053.pac",
			"ags_inds\coal.pac",
			"ags_inds\black.pac",
			"ags_inds\top_s.pac",
			"ags_inds\to_podklad2.pac",
			"ags_inds\pillar2.pac",
			"ags_inds\door3b.pac",
			
			"JOF_Objects1\wand.pac",
			"JOF_Objects1\M4.paa",
			"JOF_Objects1\M3.paa",
			"JOF_Objects1\M2.paa",
			"JOF_Objects1\M1.paa",
			"JOF_Objects1\kdum_okno_big2.paa",
			"JOF_Objects1\botanic3.pac",
			"JOF_Objects1\b1.paa",
			
			"ags_port\woodfloor.pac",
			"ags_port\top_s.pac",
			
		};
		material="#OFPbuildings";
	};
	
	class OFPAddons1Terrain
	{
		textures[]=
		{	
			"seb_ilo\garden.pac",
			"seb_ilo\dike1.paa",
			
			"BAS_O\_t\basrockd1.paa",
			"BAS_O\_t\basrockD.PAC",
			
			"BAS_O\_Td\hlinasterk.pac",
			
			"ags_inds\heli.paa",
			"ags_inds\concwall_top.pac",
			"ags_inds\concrete3b.pac",
			"ags_inds\concrete3.pac",
			"ags_inds\concrete2.pac",
			
			"ags_port\concrete2.pac",
			"ags_port\concr2_side.pac",
			"ags_port\concr_h.pac",
			
		};
		material="#OFPTerrain";
	};

	class OFPAddons1Roads
	{
		textures[]=
		{	

			"seb_ilo\p\sebtrailpath_kr.paa",
			"seb_ilo\p\sebtrailpath.paa",
			
			"BAS_O\_tbase\bridge_rd.paa",
			
			"BAS_O\_tobj\bas_roadte.paa",
			"BAS_O\_tobj\bas_roadt.paa",
			"BAS_O\_tobj\bas_roadil.paa",
			"BAS_O\_tobj\bas_roadde.paa",
			"BAS_O\_tobj\bas_roadd.paa",
			"BAS_O\_tobj\bas_roadae.paa",
			"BAS_O\_tobj\bas_roadae PALE.paa",
			"BAS_O\_tobj\bas_roada.paa",
			"BAS_O\_tobj\bas_roada PLALE.paa",
			
		};
		material="#OFPRoads";
	};
		
	class OFPAddons1Vegetation
	{
		textures[]=
			{		
			"seb_ilo\plm_t\wall2.paa",
			"seb_ilo\plm_t\wall1.paa",
			"seb_ilo\plm_t\tree4l.paa",
			"seb_ilo\plm_t\tree4.pac",
			"seb_ilo\plm_t\tree3l.paa",
			"seb_ilo\plm_t\tree3.pac",
			"seb_ilo\plm_t\tree2l.paa",
			"seb_ilo\plm_t\tree2.pac",
			"seb_ilo\plm_t\tree1_topl.pac",
			"seb_ilo\plm_t\tree1_top.pac",
			"seb_ilo\plm_t\tree1_sidel.pac",
			"seb_ilo\plm_t\tree1_side.pac",
			"seb_ilo\plm_t\tree1_lodl.pac",
			"seb_ilo\plm_t\tree1_lod.pac",
			"seb_ilo\plm_t\tree1_bark.pac",
			"seb_ilo\plm_t\smalltree1.paa",
			"seb_ilo\plm_t\roof1.paa",
			"seb_ilo\plm_t\ptopl.paa",
			"seb_ilo\plm_t\ptop.paa",
			"seb_ilo\plm_t\plant7l.paa",
			"seb_ilo\plm_t\plant7.paa",
			"seb_ilo\plm_t\plant6l.paa",
			"seb_ilo\plm_t\plant6.paa",
			"seb_ilo\plm_t\plant5l.paa",
			"seb_ilo\plm_t\plant5.paa",
			"seb_ilo\plm_t\plant4l.paa",
			"seb_ilo\plm_t\plant4.paa",
			"seb_ilo\plm_t\plant3l.paa",
			"seb_ilo\plm_t\plant3.paa",
			"seb_ilo\plm_t\plant2l.paa",
			"seb_ilo\plm_t\plant2.paa",
			"seb_ilo\plm_t\plant1l.paa",
			"seb_ilo\plm_t\plant1.paa",
			"seb_ilo\plm_t\palmtfl.paa",
			"seb_ilo\plm_t\palmtf.paa",
			"seb_ilo\plm_t\palmd.pac",
			"seb_ilo\plm_t\palmd.paa",
			"seb_ilo\plm_t\palmc.paa",
			"seb_ilo\plm_t\palmb.pac",
			"seb_ilo\plm_t\palma.paa",
			"seb_ilo\plm_t\palm4s.paa",
			"seb_ilo\plm_t\palm4f.paa",
			"seb_ilo\plm_t\palm3f.paa",
			"seb_ilo\plm_t\palm2f.paa",
			"seb_ilo\plm_t\palm1.paa",
			"seb_ilo\plm_t\lograss.pac",
			"seb_ilo\plm_t\lograss.paa",
			"seb_ilo\plm_t\leaf1.pac",
			"seb_ilo\plm_t\leaf1.paa",
			"seb_ilo\plm_t\gras3l.paa",
			"seb_ilo\plm_t\gras3.pac",
			"seb_ilo\plm_t\gras3.paa",
			"seb_ilo\plm_t\frame1.paa",
			"seb_ilo\plm_t\floor1.paa",
			"seb_ilo\plm_t\dbush4.paa",
			"seb_ilo\plm_t\dbush3.paa",
			"seb_ilo\plm_t\dbush2.paa",
			"seb_ilo\plm_t\dbush1.paa",
			"seb_ilo\plm_t\bush6l.paa",
			"seb_ilo\plm_t\bush6.paa",
			"seb_ilo\plm_t\bush5l.paa",
			"seb_ilo\plm_t\bush5.paa",
			"seb_ilo\plm_t\bush4l.paa",
			"seb_ilo\plm_t\bush4.paa",
			"seb_ilo\plm_t\bush3l.paa",
			"seb_ilo\plm_t\bush3.paa",
			"seb_ilo\plm_t\bush2l.paa",
			"seb_ilo\plm_t\bush2.pac",
			"seb_ilo\plm_t\bush2.paa",
			"seb_ilo\plm_t\bush1l.paa",
			"seb_ilo\plm_t\bush1.paa",
			"seb_ilo\plm_t\bamboo04.paa",
			
			"BAS_O\t\tabelods.paa",
			"BAS_O\t\tabebuiabrk.paa",
			"BAS_O\t\tabebuia.paa",
			"BAS_O\t\rubber1.paa",
			
			"BAS_O\_t1\treestop2.pac",
			"BAS_O\_t1\treestop.pac",
			"BAS_O\_t1\scrub2x.paa",
			"BAS_O\_t1\rings.pac",
			"BAS_O\_t1\pinuspbrk.paa",
			"BAS_O\_t1\pinusp.paa",
			"BAS_O\_t1\olivebrk.paa",
			"BAS_O\_t1\olive2.paa",
			"BAS_O\_t1\olive.paa",
			"BAS_O\_t1\masticlod.paa",
			"BAS_O\_t1\masticbrn2.paa",
			"BAS_O\_t1\masticbrn.paa",
			"BAS_O\_t1\masticbrk.paa",
			"BAS_O\_t1\log.pac",
			"BAS_O\_t1\laurus_brn.paa",
			"BAS_O\_t1\laurus_brk.paa",
			"BAS_O\_t1\grasstopg.paa",
			"BAS_O\_t1\grasstopd.paa",
			"BAS_O\_t1\grass_g1l.pac",
			"BAS_O\_t1\grass_g1.pac",
			"BAS_O\_t1\grass_dlodt.pac",
			"BAS_O\_t1\grass_d1l.pac",
			"BAS_O\_t1\grass_d1.pac",
			"BAS_O\_t1\fronds2topl.pac",
			"BAS_O\_t1\fronds2topa.pac",
			"BAS_O\_t1\fronds2sidea.pac",
			"BAS_O\_t1\fronds1topl.pac",
			"BAS_O\_t1\fronds1topa.pac",
			"BAS_O\_t1\fronds1sidea.pac",
			"BAS_O\_t1\erica_arborea.pac",
			"BAS_O\_t1\daloe.paa",
			"BAS_O\_t1\bush06lod.pac",
			"BAS_O\_t1\bush_g52x.pac",
			"BAS_O\_t1\bush_g42x.pac",
			"BAS_O\_t1\bush_g2.pac",
			"BAS_O\_t1\bush_g1.pac",
			"BAS_O\_t1\bush_d52x.pac",
			"BAS_O\_t1\bush_d42x.pac",
			"BAS_O\_t1\bush_d2.pac",
			"BAS_O\_t1\bush_d1.pac",
			"BAS_O\_t1\brg_ilexbrk.paa",
			"BAS_O\_t1\bottreebrk.paa",
			"BAS_O\_t1\bark1a.pac",
			"BAS_O\_t1\bark1.pac",
			"BAS_O\_t1\baolod.pac",
			"BAS_O\_t1\baobrk2.pac",
			"BAS_O\_t1\baobrk.pac",
			"BAS_O\_t1\aloet.paa",
			"BAS_O\_t1\aloelod.paa",
			"BAS_O\_t1\aloe1.paa",
			"BAS_O\_t1\agavpar2.pac",
			"BAS_O\_t1\acacialod.pac",
			"BAS_O\_t1\acacia.pac",
			"BAS_O\_t1\acac_brk2.pac",
			
			"BAS_O\_tmisc\spalek.pac",
			
			"BAS_O\_twood\w_01.pac",
			
			"afganO\tex\rostlina2.paa",
			"afganO\tex\palmtr.pac",
			"afganO\tex\palm2h.paa",
			"afganO\tex\palm.paa",
			"afganO\herbejaune.paa",
			
		};
		material="#OFPvegetation";
	};

	class OFPAddons1Water
	{
		textures[]=
		{	
		};
		material="#OFPWater";
	};

	class OFPAddons1Sea
	{
		textures[]=
		{	
		};
		material="#Water";
	};

	class OFPAddons1particles
	{
		textures[]=
		{				
		};
		material="#OFPparticles";
	};
	
	class OFPAddons1shiningParticles
	{
		textures[]=
		{	
			"BAS_O\_tmisc\laser.paa",
			
		};
		material="#OFPshining";
	};
	
	class OFPAddons1Faces
	{
		textures[]=
		{	
			"BAS_O\face\BAShostage2.paa",
			"BAS_O\face\BAShostage1.paa",
			"BAS_O\face\BASafrican6.paa",
			"BAS_O\face\BASafrican5.paa",
			"BAS_O\face\BASafrican4.paa",
			"BAS_O\face\BASafrican3.paa",
			"BAS_O\face\BASafrican2.paa",
			"BAS_O\face\BASafrican1.paa",
			
			"BAS_O\_tmisc\xicht_2gd.paa",
			"BAS_O\_tmisc\t_usta.pac",
			
		};
		material="#OFPskin";
	};
	
	class OFPAddons1Clothing
	{
		textures[]=
		{		
			
			"Mi2NO\pilot\top.pac",
			"Mi2NO\pilot\ruk.pac",
			"Mi2NO\pilot\rub.pac",
			"Mi2NO\pilot\pog.pac",
			"Mi2NO\pilot\kep.pac",
			
			"sebnam_obj\h\sebpytle_top_d.pac",
			"sebnam_obj\h\sebpytle_top.pac",
			"sebnam_obj\h\sebpytle_front.pac",
			"sebnam_obj\h\sebpytle_bsl.pac",
			"sebnam_obj\h\p_d.pac",
			"sebnam_obj\h\p.pac",
			"sebnam_obj\h\ont.pac",
			
			"BAS_O\sandbag\sandbag.pac",
			"BAS_O\sandbag\bwall.pac",
			
			"BAS_O\_c\stall - top.pac",
			"BAS_O\_c\stall - roof.pac",
			"BAS_O\_c\rug3.pac",
			"BAS_O\_c\rug2.pac",
			"BAS_O\_c\rug.pac",
			"BAS_O\_c\clothes.pac",
			
			"BAS_O\_t\bassofa2.pac",
			"BAS_O\_t\bassofa.pac",
			
			"BAS_O\_tmisc\pir2.paa",
			"BAS_O\_tmisc\lod-2.paa",
			"BAS_O\_tmisc\lod.paa",
			
		};
		material="#OFPclothing";
	};
	
	class OFPAddons1Gear
	{
		textures[]=
		{
			"Mi2NO\pilot\naushniki.pac",
			"Mi2NO\pilot\microfon.pac",
			"Mi2NO\pilot\kab.pac",
			"Mi2NO\pilot\duzhka.paa",
			
			"Mi2NO\pribory.pac",
			"Mi2NO\kompass.pac",
			"Mi2NO\horisont.pac",
			"Mi2NO\Gera_whellsA.paa",
			"Mi2NO\Gear_whells.pac",
			
			"seb_ilo\h\camonet.pac",
			
			"BAS_O\t\tenttop2.paa",
			"BAS_O\t\tenttop.paa",
			
			"BAS_O\_new\tent_r3.paa",
			"BAS_O\_new\tent_r2.paa",
			"BAS_O\_new\tent_r1.paa",
			"BAS_O\_new\tent_g3.paa",
			"BAS_O\_new\tent_g2.paa",
			"BAS_O\_new\tent_g1.paa",
			
			"BAS_O\_t1\ele.paa",
			
			"BAS_O\_tmisc\screen.paa",
			
			"BAS_O\_tx\cb_nadrz.paa",
			
			"afganO\stan2_eastlod_side2.pac",
			"afganO\stan2_eastlod_side.pac",
			"afganO\stan2_east_side2.pac",
			"afganO\stan2_east_side.pac",
			"afganO\stan2_east_front2.pac",
			"afganO\stan2_east_front.pac",
			"CBT_Misc\Dragon\dragon.pac",
			"CBT_Misc\jav\front.paa",
			"CBT_Misc\jav\fronttest.paa",
			"CBT_Misc\jav\javmis.paa",
			"CBT_Misc\jav\tube.paa",
			"CBT_Misc\tow\stinger.pac",
			"CBT_Misc\tow\tow.paa",

		};
		material="#OFPgear";
	};
