class CfgTextureToMaterial {
	class KamovGlass {
		textures[]={"o\vehl\V-80_frontsklo.paa"};
		material="#SpecularGlass";
	};
	class KamovMetal {
		textures[]={"\o\vehl\v-80_backwing.pac","\o\vehl\v-80_blade.pac","\o\vehl\v-80_misc1.pac","\o\vehl\v-80_misc2.pac","\o\vehl\v-80_rotor.pac","\o\vehl\v-80_rotor2.pac","\o\vehl\v-80_test4a.pac","\o\vehl\v-80_test4b2.pac","\o\vehl\v-80_testbott4a.pac","\o\vehl\v-80_testbott4b.pac","\o\vehl\v-80_testtop4a.pac","\o\vehl\v-80_testtop4b.pac","\o\vehl\v-80_testwing.pac","\o\vehl\v-80_undergun.pac","\o\vehl\v-80_unguided.pac"};
		material="#Metal";
	};

	class ETONDataMetalVeh
	{
		textures[]=
		{
			"BMP2\smoke-prefinal.pac",
			"data\ural_svetlomet.pac",

			"Apac\hell_fr.pac",
			"Apac\hell_bck.pac",
			"Apac\apach_vrtulka.paa",
			"Apac\apach_vrtule3.pac",
			"Apac\apach_vrtule2.pac",
			"Apac\apach_vrtule.pac",

			"trab\trabistrecha.pac",
			"trab\trabistrana.pac",
			"trab\trabisklaramy.pac",
			"trab\trabipredzad.pac",
			"trab\trabihaubna.pac",

			"data\zrcatko.paa",

			"data\vymetnice.pac",
			"data\vterinova.paa",

			"data\vrtule_velka_bl_.paa",
			"data\vrtule_velka.paa",
			"data\vrtule_uh_v_bl.paa",
			"data\vrtule_uh_v.paa",
			"data\vrtule_uh_m_bl.paa",
			"data\vrtule_uh_m.pac",
			"data\vrthind_m_bl.paa",
			"data\vrthind_m.paa",

			"o\Vehl\bus01.pac",
			"o\Vehl\bus01a.pac",
			"o\Vehl\bus_alfa.paa",
			"o\Vehl\bus_podvozek.pac",
			"o\Vehl\cj5_podvozek.pac",
			"o\Vehl\cj5_strana.pac",
			"o\Vehl\jawadraty.pac",
			"o\Vehl\jeep4x4_sklof.pac",
			"o\Vehl\moto01.pac",
			"o\Vehl\moto02.pac",
			"o\Vehl\moto03.pac",
			"o\Vehl\v-80_at.pac",
			"o\Vehl\v-80_backwing.pac",
			"o\Vehl\v-80_blade.pac",
			"o\Vehl\v-80_blurblade.pac",
			"o\Vehl\v-80_misc1.pac",
			"o\Vehl\v-80_misc2.pac",
			"o\Vehl\v-80_podmotlod.pac",
			"o\Vehl\v-80_raketlod.pac",
			"o\Vehl\v-80_rotor2.pac",
			"o\Vehl\v-80_rotor.pac",
			"o\Vehl\v-80_rotorlod.paa",
			"o\Vehl\v-80_side1lod.paa",
			"o\Vehl\v-80_side2lod.paa",
			"o\Vehl\v-80_test4a.pac",
			"o\Vehl\v-80_test4b2.pac",
			"o\Vehl\v-80_testbott4a.pac",
			"o\Vehl\v-80_testbott4b.pac",
			"o\Vehl\v-80_testtop4a.pac",
			"o\Vehl\v-80_testtop4b.pac",
			"o\Vehl\v-80_testwing.pac",
			"o\Vehl\v-80_undergun.pac",
			"o\Vehl\v-80_unguided.pac",
			"o\Vehl\v-80_wiretoplod.pac",

			"Brmd\brmd2_vyfuk.paa",
			"Brmd\brmd_detaily.pac",
			"Brmd\brmd_haubna.pac",
			"Brmd\brmd_lopata.paa",
			"Brmd\brmd_predek1.pac",
			"Brmd\brmd_predek2.pac",
			"Brmd\brmd_strana1.pac",
			"Brmd\brmd_strana2.pac",
			"Brmd\brmdsvetla.pac",
			"Brmd\brmdvrch1.pac",
			"Brmd\brmdvrch2.pac",
			"Brmd\brmdzadek.pac",

			"Apac\apach_side1.pac",
			"Apac\apach_side21.pac",
			"Apac\apach_side3.pac",
			"Apac\apach_side4.pac",
			"Apac\apach_side5.pac",
			"Apac\apach_up1.pac",
			"Apac\apach_up2.pac",
			"Apac\apach_up3.pac",
			"Apac\apach_det.pac",
			"Apac\apach_down1.pac",
			"Apac\hell_fr.pac",
			"Apac\hell_w.pac",
			"Apac\hell_side.pac",

			"Biscamel\cml2_bck_w.pac",
			"Biscamel\cml2_bck_wb.pac",
			"Biscamel\cml2_bot_w.pac",
			"Biscamel\cml2_bot_wb.pac",
			"Biscamel\cml2_bottom.pac",
			"Biscamel\cml2_front.pac",
			"Biscamel\cml2_land_gear.pac",
			"Biscamel\cml2_side.pac",
			"Biscamel\cml2_tail.pac",
			"Biscamel\cml2_top1.pac",
			"Biscamel\cml2_top2.pac",
			"Biscamel\cml2_top_w.pac",
			"Biscamel\cml2_top_wb.pac",
			"Biscamel\cml_bck_w.pac",
			"Biscamel\cml_bck_wb.pac",
			"Biscamel\cml_bot_w.pac",
			"Biscamel\cml_bot_wb.pac",
			"Biscamel\cml_bottom.pac",
			"Biscamel\cml_engine.pac",
			"Biscamel\cml_engine_ar.pac",
			"Biscamel\cml_front.pac",
			"Biscamel\cml_land_gear.pac",
			"Biscamel\cml_okynko.pac",
			"Biscamel\cml_podp2.pac",
			"Biscamel\cml_podpristroj.pac",
			"Biscamel\cml_side.pac",
			"Biscamel\cml_tail.pac",
			"Biscamel\cml_top1.pac",
			"Biscamel\cml_top2.pac",
			"Biscamel\cml_top_w.pac",
			"Biscamel\cml_top_wb.pac",
			"Biscamel\cml_vrtblur.pac",
			"Biscamel\cml_vrtule.pac",

			"BMP2\2a42kanon-final.paa",
			"BMP2\ammo_pkt.pac",
			"BMP2\at6-launcher.pac",
			"BMP2\back.pac",
			"BMP2\blat_s.pac",
			"BMP2\blatnik.pac",
			"BMP2\bmp2_top.pac",
			"BMP2\bmp2_vez_back.pac",
			"BMP2\bmp2_vez_frnt.pac",
			"BMP2\bvp2_kanon.paa",
			"BMP2\bvp2_kanon.pac",
			"BMP2\detaily.pac",
			"BMP2\front.paa",
			"BMP2\kolo1.paa",
			"BMP2\kolo1i.paa",
			"BMP2\kolo_hn.paa",
			"BMP2\kolo_mini.paa",
			"BMP2\kolo_zub.paa",
			"BMP2\kryt_m.pac",
			"BMP2\launcher.pac",
			"BMP2\poklopy.pac",
			"BMP2\rocket-backfront.pac",
			"BMP2\rocket-side.pac",
			"BMP2\side.pac",
			"BMP2\top.pac",
			"BMP2\veza.pac",
			"BMP2\veza_back.pac",

			"ch47\ch47_back_t.pac",
			"ch47\ch47_cumak_p.pac",
			"ch47\ch-47_end_down.pac",
			"ch47\ch-47_list.pac",
			"ch47\ch-47_mid_down.pac",
			"ch47\ch-47_motor_back.pac",
			"ch47\ch-47_motor_side.pac",
			"ch47\ch-47_side_mid.pac",
			"ch47\ch-47_side_mid2.pac",
			"ch47\ch-47_side_mid2t.paa",
			"ch47\ch-47_side_midt.paa",
			"ch47\ch-47_side_nose.pac",
			"ch47\ch-47_side_nose2.pac",
			"ch47\ch-47_side_nt.paa",
			"ch47\ch-47_side_tail.pac",
			"ch47\ch-47_side_tailt.paa",
			"ch47\ch47_strop_venku.pac",
			"ch47\ch-47_up_down.pac",
			"ch47\ch-47_veze_top.pac",
			"ch47\ch47_vratka.pac",
			"ch47\ch47_vratka-hrana.pac",
			"ch47\ch-47_vrtule.paa",
			"ch47\ch47_vrtulestred.pac",
			"ch47\desticka_nad_dvermi.pac",

			"data\5t__otevreny.pac",
			"data\5t_fuel1.pac",
			"data\5t_fuel2.pac",
			"data\5t_kab_detaily1.pac",
			"data\5t_kab_detaily2.pac",
			"data\5t_kab_haubna.pac",
			"data\5t_kab_maska.pac",
			"data\5t_kab_predek.pac",
			"data\5t_kab_strana.pac",
			"data\5t_kab_zadni.pac",
			"data\5t_pod_odpru.pac",
			"data\5tdvere.pac",
			"data\5tpredek.pac",
			"data\5tunivgreen.pac",

			"data\a10_elipse1.pac",
			"data\a10_kridlo_konecek.pac",
			"data\a10_kridlo_spod.pac",
			"data\a10_kridlo_top2.pac",
			"data\a10_motor2.pac",
			"data\a10_motor_bck.pac",
			"data\a10_motor_frnt1.pac",
			"data\a10_motor_frt.pac",
			"data\a10_motor_spodek.pac",
			"data\a10_motor_top2.pac",
			"data\a10_nosic.pac",
			"data\a10_nosic_spodek.pac",
			"data\a10_side_a2.pac",
			"data\a10_side_b2.pac",
			"data\a10_sop2.pac",
			"data\a10_trupa_spod.pac",
			"data\a10_trupa_top2.pac",
			"data\a10_trupb_spod.pac",
			"data\a10_trupb_top2.pac",
			"data\a10_vop_top2.pac",
			"data\a10_prase.paa",

			"data\abrams_svetlo_b.paa",
			"data\abrams_svetlo.paa",
			"data\abrams_roury_side.pac",
			"data\abrams_roury_frt.pac",
			"data\abrams_kolo2.pac",
			"data\abrams_kolo.pac",
			"data\m1a1_driv_darktrubka.paa",

			"data\ah-1_vedle_sedacka.pac",
			"data\ah-1_side_lod.paa",
			"data\ah-1_sedacka.pac",
			"data\ah-1_pod_sedacka2.pac",
			"data\ah-1_pod_sedacka1.pac",
			"data\ah-1_opak_pokus.pac",
			"data\ah-1_list_vrtule_gif.pac",
			"data\ah-1_list_vrtule.paa",
			"data\ah-1_bottom2.pac",
			"data\ah-1_bottom1.pac",
			"data\ah-1_2_pokus.pac",
			"data\ah-1_1_pokus.pac",

			"data\blue_sk_back_.pac",
			"data\blue_sk_front_.pac",
			"data\blue_sk_kapot.pac",
			"data\blue_sk_side2.pac",
			"data\blue_sk_strch.pac",
			"data\blue_sk_z_k.pac",

			"data\bmp_ambulance_back.pac",
			"data\bmp_ambulance_sideca.pac",
			"data\bmp_anm.01.pac",
			"data\bmp_anm.02.pac",
			"data\bmp_anm.03.pac",
			"data\bmp_anm.04.pac",
			"data\bmp_anm.05.pac",
			"data\bmp_back.pac",
			"data\bmp_ambulance_top.pac",
			"data\bmp_hlaven.pac",
			"data\bmp_hlaven.paa",
			"data\bmp_kolo.pac",
			"data\bmp_kolo2.pac",
			"data\bmp_kolo_hn.paa",
			"data\bmp_kolo_hn2.paa",
			"data\bmp_kolo_mini.paa",
			"data\bmp_kolo_zub2.paa",
			"data\bmp_kuk1.pac",
			"data\bmp_kuk2.pac",
			"data\bmp_kuk3.pac",
			"data\bmp_kulomet.pac",
			"data\bmp_lauf.pac",
			"data\bmp_lavice.paa",
			"data\bmp_lavice.pac",
			"data\bmp_lin_cislo.paa",
			"data\bmp_pantramp.pac",
			"data\bmp_plat_uni.pac",
			"data\bmp_podlauf_f.pac",
			"data\bmp_podlazka.pac",
			"data\bmp_raketa.pac",
			"data\bmp_raketapok.pac",
			"data\bmp_rocketramp.pac",
			"data\bmp_rocketramp_f.pac",
			"data\bmp_rocketramp_t.pac",
			"data\bmp_side.pac",
			"data\bmp_side_hi.pac",
			"data\bmp_top.pac",
			"data\bmp_vez_back.pac",
			"data\bmp_vez_top.pac",

			"data\cobra_rotor_side_cen.pac",
			"data\cobra_rotor_top.pac",
			"data\cobra_zuni_kridlo.pac",
			"data\cobra_zuni_plast.pac",
			"data\cobra2_kridlo_predni.pac",
			"data\cobra2_kulas_front.paa",
			"data\cobra2_kulas_side.pac",
			"data\cobra2_kulfront_fron.pac",
			"data\cobra2_vejfuk.paa",
			"data\cobra3_cumak.pac",
			"data\cobra3_spod_a.pac",
			"data\cobracidlo.paa",

			"data\green_sk_back_.pac",
			"data\green_sk_front_.pac",
			"data\green_sk_kapot.pac",
			"data\green_sk_nadrz.paa",
			"data\green_sk_side2.pac",
			"data\green_sk_side2_tga.paa",
			"data\green_sk_strch.pac",
			"data\green_sk_z_k.pac",

			"data\guaz_blatnik_top.pac",
			"data\guaz_kapota_top.pac",
			"data\guaz_komplet_side.pac",
			"data\guaz_predek_front.pac",
			"data\guaz_predek_side.pac",
			"data\guaz_zadek_front.pac",
			"data\guaz_zadek_side.pac",

			"data\hind_front_new.pac",
			"data\hind_raketomet2.pac",
			"data\hind_reketm_usti.pac",
			"data\hind_reketm_zadek.paa",
			"data\hind_reketm2_usti.paa",
			"data\hip_black.pac",
			"data\hip_cidlo_s.paa",
			"data\hip_cidlo_f.paa",
			"data\hip_cidlo_s.pac",
			"data\hip_s1.pac",
			"data\hip_s1_lod.paa",
			"data\hip_s1_nolod.pac",
			"data\hip_s1b.pac",
			"data\hip_s1b_lod.paa",
			"data\hip_s1b_nolod.pac",
			"data\hip_s1comp.pac",
			"data\hip_s2.pac",
			"data\hip_spod1.pac",
			"data\hip_spod1_comp.pac",
			"data\hip_spod2.pac",
			"data\hip_top.pac",
			"data\hip_top_comp.pac",
			"data\hip_top_okno.pac",
			"data\hip_top2.pac",
			"data\hip_vreteno_kratke.pac",
			"data\hip_vrt_v.paa",
			"data\hip_vrtblur_v.paa",
			"data\hip_zavesnik_f.pac",
			"data\hip_zavesnik_roury_s.pac",
			"data\hip_zavesnik_t.pac",
			"data\hipspodocas.pac",

			"data\jeep_antena_side.pac",
			"data\jeep_antenaspod_fron.pac",
			"data\jeep_blink_back.pac",
			"data\jeep_blink_front.pac",
			"data\jeep_kab_deska2_spod.pac",
			"data\jeep_kab_deska_spod.pac",
			"data\jeep_kab_deska_side.pac",
			"data\jeep_kab_motorek.pac",
			"data\jeep_kab_paka_side.pac",
			"data\jeep_kab_pan_rohoz_f.pac",
			"data\jeep_kab_pan_spod_fr.pac",
			"data\jeep_kab_ped_front.pac",
			"data\jeep_kab_plechy_all.pac",
			"data\jeep_kab_reflekt_bac.paa",
			"data\jeep_kab_sedlo_frnt.pac",
			"data\jeep_kab_sedlo_side.pac",
			"data\jeep_kab_sedlo_top.pac",
			"data\jeep_kab_sedlozadni_.pac",
			"data\jeep_kab_taska_side.pac",
			"data\jeep_kab_taska_top.pac",
			"data\jeep_kanistr_frontba.pac",
			"data\jeep_kanistr_side.pac",
			"data\jeep_kanistr_spod.pac",
			"data\jeep_kanistr_top.pac",
			"data\jeep_kapota2_top.pac",
			"data\jeep_naraznik_top.pac",
			"data\jeep_oblouk_front.paa",
			"data\jeep_predek_front.pac",
			"data\jeep_predek_side.pac",
			"data\jeep_reflekt_front.pac",
			"data\jeep_reflekt_side.pac",
			"data\jeep_side.paa",
			"data\jeep_spodek.pac",
			"data\jeep_zadek_front.pac",
			"data\jeep_zrcatko_back.pac",
			"data\jeepredek_lod.paa",
			"data\jeept_darkopak.pac",
			"data\jeept_lightopak.pac",
			"data\jeept_perovani.paa",
			"data\jeept_spaleniste.paa",
			"data\jeeptaf_back.pac",
			"data\jeeptaf_front.pac",
			"data\jeeptaf_kapota.pac",
			"data\jeeptaf_lightopak.pac",
			"data\jeeptaf_palubka.pac",
			"data\jeeptaf_podlaha.pac",
			"data\jeeptaf_sedacky.paa",
			"data\jeeptaf_side.pac",
			"data\jeeptaf_sidet.paa",
			"data\jeeptaf_sklo.pac",
			"data\jeeptaf_sklot.paa",
			"data\jeepzadek_lod.paa",

			"data\kobraplech.pac",
			"data\kobraplechopak.pac",

			"data\m1_passide_anim.01.pac",
			"data\m1_passide_anim.02.pac",
			"data\m1_passide_anim.03.pac",
			"data\m1_passide_anim.04.pac",
			"data\m1_passide_anim.05.pac",
			"data\m1_passide_anim.06.pac",

			"data\m113_kolo.pac",
			"data\m113_kolo2.pac",
			"data\m113_plat_uni.pac",
			"data\m113_svetla_front.pac",
			"data\m113bottom.pac",
			"data\m113bottom_lod.pac",
			"data\m113dverein.pac",
			"data\m113front.pac",
			"data\m113greenbedna.pac",
			"data\m113indark.pac",
			"data\m113kanystrfrt.pac",
			"data\m113kanystrside.pac",
			"data\m113kanystrtop.pac",
			"data\m113kolo2.paa",
			"data\m113krbbok.pac",
			"data\m113krbfrt.pac",
			"data\m113paca.pac",
			"data\m113pancir2.pac",
			"data\m113pancir.paa",
			"data\m113pancir.pac",
			"data\m113plat_uni.pac",
			"data\m113sanita-side_lod.pac",
			"data\m113sanita-top.pac",
			"data\m113slapka.pac",
			"data\m113t_svetla_front.pac",
			"data\m113top.pac",
			"data\m133_kanystr.pac",
			"data\m133_lopata.pac",
			"data\m133_naradi.paa",
			"data\m133_newback.pac",
			"data\m133_newbottom.pac",
			"data\m133_newfront.pac",
			"data\m133_newfrontlod.pac",
			"data\m133_newside.pac",
			"data\m133_newsideamb.pac",
			"data\m133_newtop.pac",
			"data\m133t_dnewkolo.paa",
			"data\m133t_dnewzubkolo.paa",
			"data\m133t_newback.pac",
			"data\m133t_newbackkolo.paa",
			"data\m133t_newbottom.pac",
			"data\m133t_newfront.pac",
			"data\m133t_newgunlod.paa",
			"data\m133t_newkola2lod.paa",
			"data\m133t_newkolalod.paa",
			"data\m133t_newkolalod.pac",
			"data\m133t_newkolo.paa",
			"data\m133t_newside.pac",
			"data\m133t_newtop.pac",
			"data\m133t_newzubkolo.pac",

			"data\m1a1_ammo_box.pac",
			"data\m1a1_bocek.pac",
			"data\m1a1_cifernik.paa",
			"data\m1a1_cifernik2.paa",
			"data\m1a1_dratram_back.paa",
			"data\m1a1_dratram_side.paa",
			"data\m1a1_drtrm_back_b.paa",
			"data\m1a1_frnt_bck_lod.pac",
			"data\m1a1_hlaven.pac",
			"data\m1a1_kolo.paa",
			"data\m1a1_main_back.pac",
			"data\m1a1_main_bottom.pac",
			"data\m1a1_main_front.pac",
			"data\m1a1_main_side.pac",
			"data\m1a1_main_side.tga",
			"data\m1a1_main_top.pac",
			"data\m1a1_vez_back.pac",
			"data\m1a1_vez_front.pac",
			"data\m1a1_vez_hatch.pac",
			"data\m1a1_vez_side.pac",
			"data\m1a1_vez_top.pac",
			"data\m1a1_vymetnice.pac",
			"data\m1kolo2.paa",

			"data\m60_lauf.pac",
			"data\m60_lauf_2.pac",
			"data\m60_poklop_driver.pac",
			"data\m60_sidepas.pac",
			"data\m60_spoj_tl.pac",
			"data\m60_svetla.paa",
			"data\m60_t_back.pac",
			"data\m60_t_front.pac",
			"data\m60_t_side.pac",
			"data\m60_t_top.pac",
			"data\m60_tc_front.pac",
			"data\m60_tc_side.pac",
			"data\m60_zadni_rantl.paa",
			"data\m60hullback.pac",
			"data\m60hullback2.pac",
			"data\m60hulldown.pac",
			"data\m60hulldown2.pac",
			"data\m60hullfront.pac",
			"data\m60hullfront2.pac",
			"data\m60hulltop.pac",
			"data\m60kolo.paa",
			"data\m60kolo.pac",
			"data\m60kolo2.paa",
			"data\m60kolo2.pac",
			"data\m60kolo3.pac",
			"data\m60kolomaly.paa",
			"data\m60kolomaly2.paa",
			"data\m60kolozub.paa",
			"data\m60kolozub2.paa",
			"data\m60pas.pac",
			"data\m60pasb.pac",
			"data\m60s.pac",

			"data\madlo.pac",

			"data\mi17_green2.pac",
			"data\mi17_green.pac",
			"data\mi17_green2.pac",

			"data\mi24_kridliko.pac",
			"data\mi24_kridlo_m.pac",
			"data\mi24_kridlo_v.pac",
			"data\mi24_nosic.pac",
			"data\mi24_rotor.pac",
			"data\mi24_side1.pac",
			"data\mi24_side2.pac",
			"data\mi24_side3.pac",
			"data\mi24_spodek.pac",
			"data\mi24_spodek_predek.pac",
			"data\mi24_spodek_zadek.pac",
			"data\mi24_vrsek.pac",
			"data\mi24_vrsek_zadek.pac",
			"data\mi24_vrt_m_kriz.paa",
			"data\mi24_vrt_v_kriz.paa",
			"data\mi24_kridilko.pac",
			"data\mi24_kridlo_m.pac",
			"data\mi24_kridlo_v.pac",
			"data\mi24_zapatky_na_kola.pac",

			"data\mutt_backg.pac",
			"data\mutt_bottom.pac",
			"data\mutt_frontg.pac",
			"data\mutt_kanystr.pac",
			"data\mutt_kapotag.pac",
			"data\mutt_sideg.pac",
			"data\mutt_sklog.pac",
			"data\mutt_steracg.paa",
			"data\mutt_svetlag.pac",
			"data\mutt_trubka.pac",

			"data\naboj_nato.pac",
			"data\pas_spod_1frame.pac",
			"data\pasy_okolo_uni.pac",

			"data\new_cess_kridltop.pac",
			"data\new_cess_krytltop.pac",
			"data\new_cess_kryt_mot.pac",
			"data\new_cess_sid_lod.paa",
			"data\new_cess_sid_lod.pac",
			"data\new_cess_vyfvrtpac",
			"data\new_cess_zadkridl.pac",
			"data\new_cessna_cumak2.pac",
			"data\new_cessna_kola.pac",
			"data\new_cessna_side1.pac",
			"data\new_cessna_side2.pac",
			"data\new_cessna_side3.pac",
			"data\new_cessna_spod1.pac",
			"data\new_cessna_spod2.pac",
			"data\new_cessna_top_bck.pac",
			"data\new_cessna_vrtblur.paa",

			"data\parts.pac",
			"data\parts2.pac",

			"data\pbr_b_radside.pac",
			"data\pbr_b_trubka.pac",
			"data\pbr_cockpit_bedn1.pac",
			"data\pbr_cockpit_f.pac",
			"data\pbr_frontb_nast.pac",
			"data\pbr_kulsid.pac",
			"data\pbr_kultop.pac",
			"data\pbr_pal_sklo.paa",
			"data\pbr_palubaa.pac",
			"data\pbr_palubab.pac",
			"data\pbr_palubka.pac",
			"data\pbr_sideB_nast.pac",
			"data\pbr_sideb.pac",
			"data\pbr_tga_det.paa",
			"data\pbr_zadek.pac",
			"data\pbr_zarovky.pac",

			"data\pk_ammo_dst.pac",
			"data\pk_ammo_1d.pac",
			"data\pk_ammo_2d.pac",
			"data\pk_new_backd.pac",
			"data\pk_new_lod_gifd_dst.pac",

			"data\plat_uni_ammo_dst.pac",
			"data\platplechu.pac",
			"data\plech_na_terc.pac",

			"data\raketa_kridlo.pac",
			"data\raketa_sidetop.pac",
			"data\raketa_tryska.pac",
			"data\raketa_valecek1.pac",
			"data\raketa_valecek1_fron.pac",
			"data\raketa_valecek2.pac",
			"data\raketomet.pac",

			"data\rapid_naraznik.pac",
			"data\rapid_narazniky.pac",
			"data\rapid_predzadp.pac",
			"data\rapid_predzady.pac",
			"data\rapid_sidep.pac",
			"data\rapid_sidey.pac",
			"data\rapid_strechap.pac",
			"data\rapid_strechay.pac",
			"data\rapid_topbackp.pac",
			"data\rapid_topbacky.pac",
			"data\rapid_toprearp.pac",
			"data\rapid_topreary.pac",

			"data\red_sk_back_.pac",
			"data\red_sk_front.pac",
			"data\red_sk_kapot.pac",
			"data\red_sk_nadrz.pac",
			"data\red_sk_side2.pac",
			"data\red_sk_side2_tga.paa",
			"data\red_sk_strch.pac",
			"data\red_sk_z_k.pac",

			"data\rotor_s.pac",

			"data\shod_plech_top.pac",

			"data\scud_drobnosti2.pac",
			"data\scud_drobnosti2_lod.pac",
			"data\scud_drobnosti.pac",
			"data\scud_front3.pac",
			"data\scud_front3_lod.pac",
			"data\scud_kabina.pac",
			"data\scud_kabina_lod.pac",
			"data\scud_lista.pac",
			"data\scud_okus.pac",
			"data\scud_raketa1.pac",
			"data\scud_raketa2.pac",
			"data\scud_raketa.pac",
			"data\scud_side.pac",
			"data\scud_side2.pac",
			"data\scud_side3.pac",
			"data\scud_side5.pac",
			"data\scud_sides.pac",
			"data\scud_strop2.pac",
			"data\scud_strop3.pac",
			"data\scud_svetlo_zad.pac",
			"data\scud_univ.pac",
			"data\scud_vrsek.pac",
			"data\scud_vrsek2.pac",
			"data\scud_vrsek3.pac",
			"data\scud_vrsek.pac",
			"data\scud_sadek.pac",
			"data\scud_zebrik.paa",

			"data\sk_back.pac",
			"data\sk_front.pac",
			"data\sk_kapot.pac",
			"data\sk_naraznik_back.pac",
			"data\sk_naraznik_front.pac",
			"data\sk_side2.pac",
			"data\sk_side2_tga.paa",
			"data\sk_strch.pac",
			"data\sk_z_k.pac",

			"data\t55_bok.pac",
			"data\t55_detaily.pac",
			"data\t55_hlaven.pac",
			"data\t55_infra.pac",
			"data\t55_kolo1.pac",
			"data\t55_kolo2.pac",
			"data\t55_lauf_f.pac",
			"data\t55_poklop.pac",
			"data\t55_predek.pac",
			"data\t55_spodek.pac",
			"data\t55_sum.pac",
			"data\t55_svetelko.pac",
			"data\t55_top.pac",
			"data\t55_vez_side.pac",
			"data\t55_zadek.pac",
			"data\t55kolozub2.paa",
			"data\t55kolozub.paa",
			"data\t55kolopred.paa",
			"data\t55kolopred2.paa",
			"data\t55s_side.pac",
			"data\t55vez_top.pac",

			"data\t72_back.pac",
			"data\t72_front.pac",
			"data\t72_gun_delo.paa",
			"data\t72_gun_delo2.pac",
			"data\t72_hlaven_s.pac",
			"data\t72_kolo.pac",
			"data\t72_kolo2.pac",
			"data\t72_kolo3.paa",
			"data\t72_kolo_kraj.pac",
			"data\t72_pixla.pac",
			"data\t72_pixla_side.pac",
			"data\t72_side2.pac",
			"data\t72_sum.pac",
			"data\t72_top.pac",
			"data\t72_vymet.pac",
			"data\t72_vymetnice.pac",
			"data\t72_zubkolo_detail2.paa",
			"data\t72_zubkolo_detail.paa",
			"data\t72pasb.pac",

			"data\truck_kis_bck.pac",
			"data\truck_kis_frnt.pac",
			"data\truck_kisna_side.pac",
			"data\truck_kisna_top.pac",
			"data\truck_korba_spod.pac",
			"data\truck_zrcatkoplech.paa",
			"data\truck_zrcatkosklo.paa",

			"data\t80_kolo1.pac",
			"data\t80_kolo2.pac",
			"data\t80d_bck.pac",
			"data\t80d_frt.pac",
			"data\t80d_lauf_top.pac",
			"data\t80d_side.pac",
			"data\t80d_spod_spol.pac",
			"data\t80d_top.pac",
			"data\t80d_vez_bck.pac",
			"data\t80d_vez_frt.pac",
			"data\t80d_vez_side.pac",
			"data\t80d_vez_top.pac",

			"data\t-72_gun_delo.paa",
			"data\tank4_passide.pac",
			"data\tank_03_kanon_frt.pac",
			"data\tank_04_bck.pac",
			"data\tank_04_bednyuvalce.pac",
			"data\tank_04_detailkanon2.pac",
			"data\tank_04_detailkanon.pac",
			"data\tank_04_frt.pac",
			"data\tank_04_krabic_back.pac",
			"data\tank_04_krabic_side.pac",
			"data\tank_04_kuspasu_top.pac",
			"data\tank_04_lauf_frt.pac",
			"data\tank_04_lauf_top.pac",
			"data\tank_04_platyzveze_s.pac",
			"data\tank_04_platyzvozu_t.pac",
			"data\tank_04_side.pac",
			"data\tank_04_spod.pac",
			"data\tank_04_spod_spol.pac",
			"data\tank_04_sud_norm.pac",
			"data\tank_04_sud_side.paa",
			"data\tank_04_top.pac",
			"data\tank_04_v_lec_norm.pac",
			"data\tank_04_v_lec_side.paa",
			"data\tank_04_vez_bck.pac",
			"data\tank_04_vez_frt.pac",
			"data\tank_04_vez_side.pac",
			"data\tank_04_vez_top.pac",
			"data\tnk04topslo.pac",

			"data\truck_cist_top.pac",
			"data\truck_cist_front.pac",
			"data\truck_cist_side.pac",
			"data\trula_stara.pac",

			"data\uaz_kanistr_front.pac",
			"data\uaz_kanistr_side.pac",
			"data\uaz_kanistr_top.pac",
			"data\uaz_kanistr_spod.pac",
			"data\uaz_kapota_top.pac",
			"data\uaz_rampred_front.pac",
			"data\uaz_reflekt_front.paa",
			"data\uaz_reflekt_back.pac",
			"data\uazfrt.pac",
			"data\uazside1.pac",
			"data\uazside2.pac",

			"data\cobra_rantloknosum.pac",
			"data\cobra2_kulas_front.paa",

			"data\uh_rotorosa_side.pac",
			"data\uh_rotorosa.pac",
			"data\uh60_antena.paa",
			"data\uh60_bordel2.paa",
			"data\uh60_bottom_new.pac",
			"data\uh60_cumak.paa",
			"data\uh60_cumak.pac",
			"data\uh60_cumak_lod.paa",
			"data\uh60_cumak_lod.pac",
			"data\uh60_infra_side.pac",
			"data\uh60_infra_spodek.pac",
			"data\uh60_infra_kridlo2.pac",
			"data\uh60_list_vrtule.pac",
			"data\uh60_list_vrtule.paa",
			"data\uh60_list_vrt_m.paa",
			"data\uh60_nadrz.paa",
			"data\uh60_nadrz.pac",
			"data\uh60_nosic_side.pac",
			"data\uh60_noha2.pac",
			"data\uh60_ocas.paa",
			"data\uh60_ocas.pac",
			"data\uh60_ocas_kridlo.paa",
			"data\uh60_ocas_kridlo.pac",
			"data\uh60_pilot_pancer.pac",
			"data\uh60_pilot_plechmat.pac",
			"data\uh60_pilot_prstrdk_d.pac",
			"data\uh60_skla1.paa",
			"data\uh60_stred.paa",
			"data\uh60_stred.pac",
			"data\uh60_top_new1.paa",
			"data\uh60_top_new1.pac",
			"data\uh60_top_new2.paa",
			"data\uh60_top_new2.pac",
			"data\uh60_vymetnice_front.paa",
			"data\uh60_vymetnice_side.paa",
			"data\uh60_vymetnice_up.paa",
			"data\uh60-motor.paa",
			"data\uh60-motor.pac",
			"data\uh_motor_bck.pac",
			"data\uh_rotor4_topspod.pac",
			"data\uh_smotor_front.pac",

			"data\ural_bedynka2_frt.pac",
			"data\ural_bedynka_frt.pac",
			"data\ural_bedynka_side.pac",
			"data\ural_blatniky.pac",
			"data\ural_blatniky_new.pac",
			"data\ural_fuel_top.pac",
			"data\ural_fuel_side.pac",
			"data\ural_fuel_zadek.pac",
			"data\ural_green.pac",
			"data\ural_kabok2.pac",
			"data\ural_kapota_new.pac",
			"data\ural_maska_new.pac",
			"data\ural_nadrz.pac",
			"data\ural_naraznik_new.pac",
			"data\ural_side_new.pac",
			"data\ural_dvereh_in.pac",
			"data\ural_dverehlod2_in.pac",
			"data\ural_dverehlod.pac",
			"data\uralt_maska_new.pac",
			"data\uralt_plachta_ram.pac",
			"data\uralt_sideh_new.pac",
			"data\uralt_sidehlod_new.pac",
			"data\uralt_sidehlod2_new.pac",
			"data\ural_repair_bck.pac",
			"data\ural_repair_frt.pac",
			"data\ural_repair_side.pac",
			"data\ural_repair_top.pac",
			"data\ural_zadek.pac",
			"data\ural_strecha_new.pac",
			"data\ural_zebrik.paa",
			"data\uralt_sedacka_pera.pac",
			"data\uralt_zrcatka1.paa",
			"data\uralt_zrcatka2.paa",

			"data\v3s_fuel_drzak.paa",
			"data\v3s_fuel_side2_.pac",
			"data\v3s_fuel_sum2.pac",
			"data\v3s_fuel_sum.pac",
			"data\v3s_kabina_b.pac",
			"data\v3s_kabina_f.pac",
			"data\v3s_kabina_t.pac",
			"data\v3s_kapota_plech.pac",
			"data\v3s_repair_bck.pac",
			"data\v3s_repair_frt.pac",
			"data\v3s_repair_side.pac",
			"data\v3s_repair_top.pac",
			"data\v3s_spodek.pac",
			"data\v3sfueltop2.pac",
			"data\v3s_zrc_l_f.paa",
			"data\v3s_zrc_r_f.paa",

			"data\zetor_back.pac",
			"data\zetor_back_konstr.pac",
			"data\zetor_back_tga.paa",
			"data\zetor_cumak.pac",
			"data\zetor_front.pac",
			"data\zetor_front_tga.paa",
			"data\zetor_kapota.pac",
			"data\zetor_motor_side.pac",
			"data\zetor_red.pac",
			"data\zetor_side_1.pac",
			"data\zetor_side_1_tga.paa",
			"data\zetor_side_2.pac",

			"data\zsu_back2.pac",
			"data\zsu_back2_lod.pac",
			"data\zsu_front2.pac",
			"data\zsu_front2_lod.pac",
			"data\zsu_hydraulika.paa",
			"data\zsu_kolo_new.pac",
			"data\zsu_kolo_okolo.pac",
			"data\zsu_kolo_zuby.pac",
			"data\zsu_pasy_side2.pac",
			"data\zsu_plech.pac",
			"data\zsu_radar_side.pac",
			"data\zsu_radar_top2.pac",
			"data\zsu_refl_frt.pac",
			"data\zsu_side2.pac",
			"data\zsu_spod.pac",
			"data\zsu_spod_lod.pac",
			"data\zsu_strana.pac",
			"data\zsu_top.pac",
			"data\zsu_vez_pruh.pac",
			"data\zsu_vez_top.pac",
			"data\zsu_vzpery.pac",
			"data\zsu_kolo_hnac.pac",

			"data\kovnavez_jehlan.pac",

			"humr\hmmwv_frntbck.pac",
			"humr\hmmwv_kapota.pac",
			"humr\hmmwv_pero.pac",
			"humr\hmmwv_predni_sklo.pac",
			"humr\hmmwv_sid1.pac",
			"humr\hmmwv_sid2.pac",
			"humr\hmmwv_side_tga.paa",
			"humr\hmmwv_strecha.pac",
			"humr\hmmwv_strecha2.pac",

			"kolo\kolo01_prevod.pac",
			"kolo\kolo01.pac",
			"kolo\koloriditka.pac",
			"kolo\koloside.pac",

			"m2a2\m2a2_back.pac",
			"m2a2\m2a2_bk.pac",
			"m2a2\m2a2_dn.pac",
			"m2a2\m2a2_down.pac",
			"m2a2\m2a2_opak2.pac",
			"m2a2\m2a2_pasbok.pac",
			"m2a2\m2a2_sid1a.pac",
			"m2a2\m2a2_sid1b.pac",
			"m2a2\m2a2_sid2a.pac",
			"m2a2\m2a2_sid2b.pac",
			"m2a2\m2a2_sida.pac",
			"m2a2\m2a2_sidb.pac",
			"m2a2\m2a2_svetla.pac",
			"m2a2\m2a2_up.pac",
			"m2a2\m2a2_upa.pac",
			"m2a2\m2a2_upb.pac",
			"m2a2\m2a2_upvez.pac",
			"m2a2\m2a2_upveza.pac",
			"m2a2\m2a2_upvezb.pac",
			"m2a2\m2a2_upvezc.pac",
			"m2a2\m2a2_upvezd.pac",
			"m2a2\m2a2_vezpruh.pac",
			"m2a2\m2a2_vez_op.pac",
			"m2a2\m2a2_vez_op2.pac",

			"Mini\mini_back2_b.pac",
			"Mini\mini_back2_lod_b.paa",
			"Mini\mini_down.paa",
			"Mini\mini_kapota_b.pac",
			"Mini\mini_maska_b.pac",
			"Mini\mini_narazniki_b.pac",
			"Mini\mini_pred_sklo_l_b.paa",
			"Mini\mini_predni_sklo_b.pac",
			"Mini\mini_predsk_in_l_b.pac",
			"Mini\mini_side_b.pac",
			"Mini\mini_side_lod_b.paa",
			"Mini\Mini_strecha_b.pac",
			"Mini\Mini_zadni_brzda.paa",
			"Mini\Mini_zadni_svetlo.pac",

			"lada\esi.pac",
			"lada\kapot.pac",
			"lada\kulg1.pac",
			"lada\kulg2.pac",
			"lada\kulg3.pac",
			"lada\kulg4.pac",
			"lada\link.paa",
			"lada\number.paa",
			"lada\pagas.pac",
			"lada\stange.pac",
			"lada\tagu.pac",

			"oh58\7-hydra-fb.pac",
			"oh58\kiowa_bottom.pac",
			"oh58\kiowa_lyz_f1.paa",
			"oh58\kiowa_lyzsid.paa",
			"oh58\kiowa_nose.pac",
			"oh58\kiowa_nosice.paa",
			"oh58\kiowa_sidetga.paa",
			"oh58\kiowa_svrtblur.paa",
			"oh58\kiowa_top.pac",
			"oh58\kiowa_v_tail.pac",
			"oh58\kiowa_vrtblur.paa",
			"oh58\kiowa_vrtule.pac",
			"oh58\kiowa-koule.pac",
			"oh58\kiowa-koulet.pac",
			"oh58\kiowa-podkoule.pac",
			"oh58\kiowa-top.pac",
			"oh58\kiowa-winglets.pac",
			"oh58\oh58_rez_top.paa",
			"oh58\oh58_sid1.pac",
			"oh58\oh58_sid2.pac",

			"SU25\su25_ch-29t.pac",
			"SU25\su25_detaily.pac",
			"SU25\su25_kulatosti.pac",
			"SU25\su25_motor1.pac",
			"SU25\su25_motorin.pac",
			"SU25\su25_raketomet.pac",
			"SU25\su25_sop.pac",
			"SU25\su25_spodek.pac",
			"SU25\su25_strana1.pac",
			"SU25\su25_strana2.pac",
			"SU25\su25_strana3.pac",
			"SU25\su25_vop.pac",
			"SU25\su25_vopspod.pac",
			"SU25\su_kridlo1.pac",
			"SU25\su_kridlo2.pac",
			"SU25\su_kridlokon.pac",
			"SU25\su_kridlospod.pac",

			"Vulcan\vulcan1.pac",
			"Vulcan\vulcan2.pac",
			"Vulcan\vulcan4.pac",
			"Vulcan\vulcan_1.pac",
			"Vulcan\vulcan_2.pac",
			"Vulcan\vulcan_3.pac",
			"Vulcan\vulcan_4.pac",
			"Vulcan\vulcan_hlavne.pac",
			"Vulcan\vulcan_kolas.pac",
			"Vulcan\vulcan_ku4l.pac",
			"Vulcan\vulcan_kukr.paa",
			"Vulcan\vulcan_kukr.pac",
			"Vulcan\vulcan_kul2.pac",
			"Vulcan\vulcan_kul3.pac",
			"Vulcan\vulcan_naboje.pac",
			"Vulcan\vulcan_newtop.pac",
			"Vulcan\vulcan_side.pac"
		};
		material="#ETONmetalVeh";
	};


	class CarGlass
		{
		textures[]={"data\jeep4x4_glass.paa","data\jeep_kab_sklo1.paa","data\jeep_kab_sklo2.paa","data\jepp4x4_glass.paa","data\jepp_kab_sklo1.paa","data\jepp_kab_sklo2.paa","data\scud_sklo.paa","data\scud_sklo2.paa","data\scud_sklo3.paa","data\scud_sklo4.paa","acr_lr\Jepp4x4_glass.paa","acr_lr\Jepp4x4_glass.paa","acr_lr\mrize.paa"};
		material="#SpecularGlass";
		};

	class AirborneGlass
		{
		textures[]={"data\jeep_kab_sklo1.paa","data\uh60_kab_sklo2.paa","data\uh30_cargo_pilotdoors.paa","data\uh60_cargo_dvereokno.paa","data\uh60_gunner_okna.paa","data\ah-1_kabina_predokno.paa","data\ah-1_kabina_zadokno.paa","data\ah-1_kabina_topokno.paa","csla_air\l410\skl.paa","csla_air\l410\skl_pil.paa"};
		material="#SpecularGlass";
		};

	class Metal
		{
		textures[]={"data\mutt_frontg.pac","data\mutt_kapotag.pac","data\mutt_sklog.pac","data\mutt_sideg.pac","o\vehl\v-80_frontsklo.paa"};
		material="#Metal";
		};

	class RifleMetal0
	{
		textures[]=
		{
			"6G30\6g30_detaily.pac",
			"6G30\6g30_drzadlo.pac",
			"6G30\6g30_hlaven.pac",
			"6G30\6g30_lod.pac",
			"6G30\6g30_rukojet.pac",
			"6G30\6g30_trubka.pac",
			"6G30\6g30_valce.pac",
			"data\ak47_v58_1d.pac",
			"data\ak47_v58_2d.pac",
			"data\ak47_v58_backd.pac",
			"data\ak47_v58_mirtopd.pac",
			"data\ak47_v58_upd.pac",
			"data\ak_granatometd.pac",
			"data\ak47_mortar.pac",
			"data\ak47_new_sumd.pac",
			"data\ak47_newr1d.pac",
			"data\ak47_newr2d.pac",
			"data\ak47_newrs1d.pac",
			"data\ak47_newrs2d.pac",
			"data\ak47_tank_back.pac",
			"data\ak47_tank_mir2_top.pac",
			"data\ak47_tank_mir2b_top.pac",
			"data\ak47_tank_sum.pac",
			"data\ak74_tank_1.pac",
			"data\ak74_tank_1s.pac",
			"data\ak74_tank_2.pac",
			"data\ak74_tank_2s.pac",
			"data\ak74_newr1d.pac",
			"data\ak74_newr2d.pac",
			"data\ak74_newrs1d.pac",
			"data\ak74_newrs2d.pac",
			"data\shmel_details.pac",
			"data\shmel_roura.pac",
			"data\shmel_roura_lod.pac",
			"O\Guns\beretta.paa",
			"O\Guns\berreta_low.pac",
			"Bizon\bizon_1d.paa",
			"Bizon\bizon_2d.paa",
			"Bizon\bizon_3d.paa",
			"Bizon\bizon_lod.pac",
			"O\Guns\cz_75.paa",
			"O\Guns\cz-75_low.pac",
			"data\stinger_chladic.paa",
			"data\stinger_chladic_gif.pac",
			"data\stinger_lod.pac",
			"data\stinger_side_gif.pac",
			"O\Guns\fal.paa",
			"O\Guns\fal_low.pac",
			"O\Guns\hk_g3a4.paa",
			"O\Guns\hk_g3a4_low.pac",
			"G36a\g36_a.paa",
			"G36a\g36_b.paa",
			"G36a\g36_b.paa",
			"G36a\g36_lod.pac",
			"data\hk_1.pac",
			"data\hk_2.pac",
			"data\hk_3.pac",
			"data\hk_lod_gif.pac",
			"data\hk_miridlo.pac",
			"O\Guns\glock_body.paa",
			"O\Guns\glock_low.pac",
			"data\law_lod.pac",
			"data\law_side_final_gif.pac",
			"data\m16_pmp_1.pac",
			"data\m16_pmp_1s.pac",
			"data\m16_pmp_g_lod.pac",
			"data\m16_pmp_granatomet.pac",
			"data\m16_pmp_ph.pac",
			"data\m2lod_ammobox.pac",
			"data\m2mg_ammobo2.pac",
			"data\m2mg_ammobox.pac",
			"data\m2mg_around.pac",
			"data\m2mg_barell.pac",
			"data\m2mg_dirky.pac",
			"data\m2mg_dirkyg.pac",
			"data\m2mg_dirkypbr.pac",
			"data\m2mg_frntbck.pac",
			"data\m2mg_kloub1.pac",
			"data\m2mg_miridla+.pac",
			"data\m2mg_noha.pac",
			"data\m2mg_rukojettop.pac",
			"data\m2mg_stoj2box.pac",
			"data\m4_1.pac",
			"data\m4_2.pac",
			"data\m4_miridla.pac",
			"data\xm177_1.pac",
			"data\xm177_1s.pac",
			"data\xm177_details.pac",
			"data\xm177_ph.pac",
			"XMS\xms_1.paa",
			"XMS\xms_1s.paa",
			"XMS\xms_details.paa",
			"XMS\xms_lod.pac",
			"XMS\xms_ph.paa",
			"XMS\xms_phn.paa",
			"XMS\xms_scope.paa",
			"XMS\xms_scope2.paa",
			"XMS\xms_scope4.paa",
			"data\m60_lauf.pac",
			"data\m60_mg_1_d.pac",
			"data\m60_mg_2_d.pac",
			"data\m60_mg_ammobox_d.pac",
			"data\m60_mg_lod_gif.pac",
			"data\cg84mm_podscop_gif.pac",
			"data\cg84mm_roura_gif.pac",
			"Mm-1\mm-1_sided2.paa",
			"Mm-1\mm-1_lod_tr.pac",
			"Mm-1\mm-1_lod_buben.paa",
			"Mm-1\mm-1_fb.paa",
			"data\pk_ammo_dsd.pac",
			"data\pk_new_1d.pac",
			"data\pk_new_backd.pac",
			"data\rpg1.pac",
			"data\rpg2.pac",
			"data\sam_roura1.paa",
			"data\sam_roura1_gif.pac",
			"data\sam_roura2_gif.pac",
			"data\sam_rukojet_gif.pac",
			"O\Guns\sa-61_low.pac",
			"O\Guns\skorpion sa-61 kver.paa",
			"Steyr\steyr_lauf.paa",
			"O\Guns\tokarevt33.paa",
			"O\Guns\tt33_low.pac",
			"O\Guns\uzi.paa",
			"O\Guns\uzi_low.pac",
			"O\Guns\uzi-sil.paa",
			"data\eminabot.pac",
			"data\eminaside.pac",
			"data\eminatop.pac",
			"data\wapminatop.pac",
			"data\wminatop.pac",
			"data\wminaside.pac",
			"data\wminabot.pac"
		};
		material="#RifleMetal0";
	};


	class RifleMetal
		{
		textures[]={"data\m16_pmp_1s.pac","data\m16_pmp_ph.pac","data\m16_pmp_lod.paa","data\m16_pmp_lod_gif.pac","data\m4_1.pac","data\m4_2.pac","data\m4_miridla.pac","data\xm177_1s.pac","data\xm177_ph.pac","data\xm177_details.pac","csla\Uk59\uk59.pac","csla\Uk59\uk59_new.paa","csla\Uk59\miridla.paa","csla\pk\pk_text.paa","csla\pk\pk_naboje.pac","csla\svd\sklicko.paa","csla\vojak\helma_side.pac","csla\vojak\helma_side_d.pac","csla\vojak\helma_f.pac","csla\vojak\helma_f_d.pac","acr_wld\wp\MP5SD6_a.paa","acr_wld\wp\MP5SD6_c.paa","acr_wld\wp\OKO_a.paa","csla_us\m16a2\a.paa","csla_us\m16a2\M203_a.paa","csla_us\m16a2\c.paa","csla_us\m4a1\a.paa","csla_us\m4a1\c.paa","csla_us\m4a1\M68_a.paa","csla_us\m4a1\M68_b.paa","csla_rus\ak\ak74_zas.pac","csla_rus\ak\ak74p_zas.pac","csla_rus\ak\Mag.paa","csla_rus\ak\ak74_ruk.pac","csla_rus\ak\akm_ruk.pac","csla_rus\ak\akmc_ruk.paa","csla_rus\ak\aks74u_ruk.pac","csla\stinger\set01.pac","csla\stinger\set02.pac","csla\stinger\stinger_LOD.pac","csla_fia\gaz69\dshk.pac","csla_fia\uni\dshk.pac","csla\vojak\prilba.pac","csla\vojak\prilba_d.pac","csla_des\sol\prilba.pac","csla_des\sol\prilba_d.pac","csla_us\wl\chelm_inn.paa","csla_us\wl\chelm_sid.paa","csla_us\wl\chelm_sidd.paa","csla_us\wl\chelm_tp.paa","csla_us\wl\chelm_tpd.paa","csla_us\wl\cmich_sid.paa","csla_us\wl\cmich_sidd.paa","csla_us\wl\cmich_tp.paa","csla_us\wl\cmich_tpd.paa","VBSWP1\wpn_pkm.paa","G36a\g36_a.paa","G36a\g36_b.paa","G36a\g36_lod.pac","Bizon\bizon_1d.paa","Bizon\bizon_2d.paa","Bizon\bizon_3d.paa","Bizon\bizon_lod.pac","O\Guns\skorpion sa-61 kver.paa","O\Guns\uzi.paa","O\Guns\uzi-sil.paa","SJB_TOSM4\m21\1.pac","SJB_TOSM4\m21\2.pac","SJB_TOSM4\m21\3.pac","SJB_TOSM4\m14\1.pac","SJB_TOSM4\m14\2.pac","SJB_TOSM4\m14\5.pac","SJB_TOSM4\m14\7.pac","SJB_TOSM4\m21\4.pac","SJB_TOSM4\m21\4d.paa","SJB_TOSM4\m21\7.pac","SJB_TOSM4\m21\grey.paa","SJB_TOSM4\m21\m161.paa","SJB_TOSM4\m21\scope.pac","SJB_TOSM4\m82\map4.pac","SJB_TOSM4\tex\map4_.paa","SJB_TOSM4\tex\sk04.paa","VBSWP1\law_side_final_gif.pac","kegrpg7\hull.pac"};
		material="#RifleMetal";
		};

	class RifleMetal2
		{
		textures[]={"RHS_RFMI\ssh68_top.paa","csla_rus\vojak\ssh68_top.paa","csla_rus\vojak\ssh68_top_d.paa","CBT_Crew\co\d_he_sid.pac","CBT_Crew\co\w_he_sid.pac","CBT_Crew\wl\mic1.paa","CBT_Crew\wl\mic2.paa","CBT_Crew\wl\mic3.paa","CBT_Crew\co\mic.paa"};
		material="#RifleMetal2";
		};

	class RifleMetalAK74P
		{
		textures[]={"csla_rus\ak\ak74p_ruk.paa","csla_rus\ak\ak74su_zas.paa"};
		material="#RifleMetalAK74P";
		};

	class RifleMetalG36
		{
		textures[]={"G36a\g36_a.paa","G36a\g36_b.paa","G36a\g36_lod.pac","G36a\g36_c.paa","ffur_res\ssh68_top_res.paa"};
		material="#RifleMetalG36";
		};

	class RifleMetallow
		{
		textures[]={"WEP_add\bizon_co.paa","WEP_add\aks74u_silencer_co.paa","csla_rus\ak\PBS2.paa","csla_rus\ak\PBS5.paa","csla_rus\ak\Side1.paa","csla_rus\ak\Butt.paa","csla\Sa58\sa58telo.pac","csla\Sa58\pazba.pac","csla_rus\ak\ak74_hlav.paa","csla_rus\ak\hlav2.paa","csla_rus\ak\ak74_stred.paa","csla_rus\ak\ak_stred_dirt.paa","csla_rus\ak\akmc_stred.paa","csla_rus\ak\ak47_zas.paa","csla_rus\ak\ak47_zas_d.paa","csla_rus\ak\akm_hlav.paa","csla_rus\ak\aks74u_zb.paa","csla_rus\ak\gp25.paa","csla_rus\ak\gp25b.paa","LSR_uswp\m60\e4.paa","LSR_uswp\m60\m60_2.paa","LSR_uswp\m60\m60_3.paa","LSR_uswp\m60\m60_4.paa","LSR_uswp\m60\m60_4.paa","SUCHusmc\frearpiece.paa","SUCHusmc\frgoggle.pac","CBT_Crew\co\goggles_lens.paa","csla_us\wl\g_glass.paa"};
		material="#RifleMetallow";
		};

	class AirMetallow
		{
		textures[]={"csla_us\uh-60a\boky.pac","csla_us\uh-60a\bottom.pac","csla_us\uh-60a\detaily.pac","csla_us\uh-60a\detaily2.paa","csla_us\uh-60a\front.pac","csla_us\uh-60a\kridlo.pac","csla_us\uh-60a\listy.pac","csla_us\uh-60a\motor.pac","csla_us\uh-60a\nadrze.pac","csla_us\uh-60a\nos.pac","csla_us\uh-60a\podvozek.pac","csla_us\uh-60a\posuvokna.pac","csla_us\uh-60a\rotor.pac","csla_us\uh-60a\sidea.pac","csla_us\uh-60a\sideb.pac","csla_us\uh-60a\topa.pac","csla_us\uh-60a\wsideb.pac","csla_us\uh-60a\zadkolo.pac","csla_us\uh-60a\zadkridlo.pac","csla_us\uh-60a\backblur.paa","csla_us\uh-60a\mainblur.paa",};
		material="#AirMetallow";
		};

	class CessnaMetal
		{
		textures[]={"data\new_cessna_cumak2.pac","data\new_cessna_kola.pac","data\new_cessna_side1.pac","data\new_cessna_side2.pac","data\new_cessna_side3.pac","data\new_cessna_spod1.pac","data\new_cessna_spod2.pac","data\new_cessna_top_bck.pac","data\new_cess_kridltop.pac","data\new_cess_kryt_mot.pac","data\new_cess_sid_lod.paa","data\new_cess_zadkridl.pac","o\vehl\moto01.pac","o\vehl\moto02.pac","o\vehl\moto03.pac"};
		material="#CessnaMetal";
		};

	class MiscMetal
		{
		textures[]={"data\5t__otevreny.pac","data\5t_fuel1.pac","data\5t_fuel2.pac","data\5t_kab_detaily1.pac","data\5t_kab_detaily2.pac","data\5t_kab_haubna.pac","data\5t_kab_maska.pac","data\5t_kab_predek.pac","data\5t_kab_strana.pac","data\5t_kab_zadni.pac","data\5tdvere.pac","data\5tdverehorni.pac","data\5thasicak.pac","data\5thasicakbotom.pac","data\5thasicaktop.pac","data\5thasicakvent.pac","data\5tmadlo.pac","data\5tpaka.pac","data\5tpakavol.pac","data\5tpalubkatop.pac","data\5tpant.pac","data\5tpant2.pac","data\5tpredek.pac","data\5trazeni.pac","O\Vehl\bus01.pac","O\Vehl\bus01a.pac","O\Vehl\cj5_strana.pac","humr\hmmwv_frntbck.pac","humr\hmmwv_kapota.pac","humr\hmmwv_sid1.pac","humr\hmmwv_sid2.pac","humr\hmmwv_side_tga.paa","humr\hmmwv_strecha.pac","humr\hmmwv_strecha2.pac","data\guaz_blatnik_top.pac","data\guaz_kapota_top.pac","data\guaz_komplet_side.pac","data\guaz_predek_front.pac","data\guaz_predek_side.pac","data\guaz_zadek_front.pac","data\guaz_zadek_side.pac","data\hrl_armor.pac","data\hrl_backgun.pac","data\hrl_hydra_side.pac","data\hrl_plech.pac","data\hrl_radar_side.pac","data\hrl_radar_top2.pac","data\hrl_side_nast.pac","data\hrl_strecha.pac","data\jeep_predek_front.pac","data\jeep_predek_side.pac","data\jeep_side.paa","data\jeep_zadek_front.pac","data\jeep_zadek_side.pac","data\jeep_zrcatko_back.pac","data\jeep_zrcatko_front.pac","data\jeepredek_lod.paa","data\jeepkolo.paa","data\mutt_kapotag.pac","data\mutt_backg.pac","data\mutt_frontg.pac","data\mutt_sideg.pac","data\mutt_sklog.pac","O\Vehl\moto01.pac","O\Vehl\moto02.pac","O\Vehl\moto03.pac","data\pbr_b_radside.pac","data\pbr_b_trubka.pac","data\pbr_cockpit_bedn1.pac","data\pbr_cockpit_f.pac","data\pbr_frontb_nast.pac","data\pbr_kulsid.pac","data\pbr_kultop.pac","data\pbr_palubaa.pac","data\pbr_palubab.pac","data\pbr_palubka.pac","data\pbr_sideb.pac","data\pbr_sideb_nast.pac","data\pbr_zadek.pac","data\scud_front3.pac","data\scud_front3_lod.pac","data\scud_lista.pac","data\scud_raketa2.pac","data\scud_side.pac","data\scud_side2.pac","data\scud_side3.pac","data\scud_side5.pac","data\scud_sides.pac","data\scud_strop2.pac","data\scud_strop3.pac","data\scud_svetlo_zad.pac","data\scud_vrsek.pac","data\scud_vrsek2.pac","data\scud_vrsek3.pac","data\scud_zadek.pac","data\scud_zebrik.paa","data\blue_sk_back_.pac","data\blue_sk_dvere_in.pac","data\blue_sk_dvere_in_zad.pac","data\blue_sk_front_.pac","data\blue_sk_kapot.pac","data\blue_sk_predni_sloup.pac","data\blue_sk_side2.pac","data\blue_sk_side2_tga.paa","data\blue_sk_strch.pac","data\blue_sk_z_k.pac","data\green_sk_back_.pac","data\green_sk_dvere_in.pac","data\green_sk_dvere_in_za.pac","data\green_sk_front_.pac","data\green_sk_kapot.pac","data\green_sk_predni_slou.pac","data\green_sk_side2.pac","data\green_sk_side2_tga.paa","data\green_sk_strch.pac","data\green_sk_z_k.pac","data\red_sk_back_.pac","data\red_sk_dvere_in.pac","data\red_sk_dvere_in_zadn.pac","data\red_sk_front_.pac","data\red_sk_kapot.pac","data\red_sk_predni_sloupe.pac","data\red_sk_side2.pac","data\red_sk_side2_tga.paa","data\red_sk_strch.pac","data\red_sk_z_k.pac","data\sk_back.pac","data\sk_front.pac","data\sk_kapot.pac","data\sk_naraznik_back.pac","data\sk_naraznik_front.pac","data\sk_predni_sloupek.pac","data\sk_side2.pac","data\sk_side2_tga.paa","data\sk_strch.pac","data\sk_z_k.pac","data\rapid_narazniky.pac","data\rapid_predzadp.pac","data\rapid_predzady.pac","data\rapid_sidep.pac","data\rapid_sidey.pac","data\rapid_strechap.pac","data\rapid_strechay.pac","data\rapid_topbackp.pac","data\rapid_topbacky.pac","data\rapid_toprearp.pac","data\rapid_topreary.pac","trab\trabihaubna.pac","trab\trabiinpredek.pac","trab\trabiinstrecha.pac","trab\trabiinzadek.pac","trab\trabipredzad.pac","trab\trabistrana.pac","trab\trabistrecha.pac","data\uaz_kanistr_front.pac","data\uaz_kanistr_side.pac","data\uaz_kanistr_spod.pac","data\uaz_kapota_top.pac","data\uazfrt.pac","data\uazkolo.paa","data\uazkolo.pac","data\uazside1.pac","data\uazside2.pac","data\uazdeskasani.pac","data\uaztop.pac","data\ural_bedynka_frt.pac","data\ural_bedynka_side.pac","data\ural_bedynka2_frt.pac","data\ural_blatniky.pac","data\ural_blatniky_new.pac","data\ural_fuel_side.pac","data\ural_fuel_top.pac","data\ural_fuel_zadek.pac","data\ural_green.pac","data\ural_in_back.pac","data\ural_in_deska.pac","data\ural_in_dvere.pac","data\ural_in_kryt.pac","data\ural_in_okno.pac","data\ural_in_top.pac","data\ural_kabok2.pac","data\ural_kapota_new.pac","data\ural_maska_new.pac","data\ural_nadrz.pac","data\ural_naraznik_new.pac","data\ural_repair_bck.pac","data\ural_repair_frt.pac","data\ural_repair_side.pac","data\ural_repair_top.pac","data\ural_side_new.pac","data\ural_skloram2_new.pac","data\ural_strecha_new.pac","data\ural_zadek.pac","data\ural_zebrik.paa","data\uralt_dvereh_in.pac","data\uralt_dverehlod_in.pac","data\uralt_dverehlod2_in.pac","data\uralt_dverelod.pac","data\uralt_maska_new.pac","data\uralt_plachta_ram.paa","data\uralt_sedacka_pera.pac","data\uralt_sideh_new.pac","data\uralt_sidehlod_new.pac","data\uralt_sidehlod2_new.pac","data\uralt_skloram2.pac","data\v3s_deskaokno.pac","data\v3s_fuel_side2_.pac","data\v3s_kabina_b.pac","data\v3s_kabina_f.pac","data\v3s_kabina_s.pac","data\v3s_kapota_t.pac","data\truck_cist_front.pac","data\truck_cist_side.pac","data\truck_cist_top.pac","data\ammobox_side.pac","data\ammobox_top.pac","data\ammobox1_front.pac","data\ammobox2_front.pac","data\nvg_tex.pac","data\dalekohled_fb.pac","data\dalekohled_r.pac","data\e_baterka_predek.pac","data\e_baterka_side.pac","data\e_baterka_spodek.pac","data\e_baterka_vrsek.pac","data\e_baterka_zadek.pac","data\e_helma_front.pac","data\e_helma_side.pac","data\e_pilot_helma_z.pac","data\e_pilot_helma_z_d.pac","data\fueltank_top.pac","data\fueltank_top2.pac","data\fueltank_side.pac","data\fuel_zabr.pac","data\fuel_zadek2.pac","data\redbarel.pac","data\redbarel_top.pac","data\rustbarel.pac","data\rustbarel2.pac","data\rustbarel2_top.pac","data\rustbarel3.pac","data\rustbarel3_top.pac","data\kos_f.paa","data\kos_floor2.paa","data\kos_s.paa","LSR_uswp\m60\e4.paa","LSR_uswp\m60\m60_2.paa","LSR_uswp\m60\m60_3.paa","LSR_uswp\m60\m60_4.paa","LSR_uswp\m60\m60_4.paa"};
		material="#MiscMetal";
		};

	class CSLA2_MetalAir
		{
		textures[]={"data\a10_kanon_front.pac","data\a10_kanon_side2.pac","data\a10_knipl.pac","data\a10_kridlo_konecek.pac","data\a10_kridlo_spod.pac","data\a10_kridlo_top2.pac","data\a10_motor_bck.pac","data\a10_motor_frnt1.paa","data\a10_motor_frt.pac","data\a10_motor_spodek.pac","data\a10_motor_top2.pac","data\a10_motor2.pac","data\a10_noha_front.paa","data\a10_noha_side.paa","data\a10_nosic.pac","data\a10_nosic_spodek.pac","data\a10_side_a2.pac","data\a10_side_b2.pac","data\a10_sop2.pac","data\a10_trupa_spod.pac","data\a10_trupa_top2.pac","data\a10_trupb_spod.pac","data\a10_trupb_top2.pac","data\a10_vop_top2.pac","data\ah-1_1_pokus.pac","data\ah-1_2_pokus.pac","data\ah-1_bottom1.pac","data\ah-1_bottom2.pac","data\ah-1_opak_pokus.pac","data\ah-1_pod_sedacka1.pac","data\ah-1_pod_sedacka2.pac","data\ah-1_side_lod.paa","data\ah-1_vedle_sedacka.pac","data\cobra2_kanon_front_b.pac","data\cobra2_kanon_side.pac","data\cobra2_kridlo_predni.pac","data\cobra2_kulas_front.paa","data\cobra2_kulas_side.pac","data\cobra2_kulfront_fron.pac","data\cobracidlo.paa","Apac\apach_side1.pac","Apac\apach_side21.pac","Apac\apach_side3.pac","Apac\apach_side4.pac","Apac\apach_side5.pac","Apac\apach_up1.pac","Apac\apach_up2.pac","Apac\apach_up3.pac","Apac\apach_vrtule.pac","Apac\apach_vrtule2.pac","Apac\apach_vrtule3.pac","Apac\apach_det.pac","Apac\apach_down1.pac","data\mave_bck.pac","data\mave_fr.pac","data\mave_side.pac","data\mave_w.pac","data\new_cess_sid_lod.pac","ch47\ch47_back_t.pac","ch47\ch-47_mid_down.pac","ch47\ch-47_motor_side.pac","ch47\ch-47_motor_back.pac","ch47\ch-47_side_mid.pac","ch47\ch-47_side_mid2.pac","ch47\ch-47_side_mid2t.paa","ch47\ch-47_side_midt.paa","ch47\ch-47_side_nose.pac","ch47\ch-47_side_nose2.pac","ch47\ch-47_side_nt.paa","ch47\ch-47_side_tail.pac","ch47\ch-47_side_tailt.paa","ch47\ch47_strop_venku.pac","ch47\ch-47_veze_top.pac","O\Vehl\v-80_at.pac","O\Vehl\v-80_backwing.pac","O\Vehl\v-80_blade.pac","O\Vehl\v-80_misc1.pac","O\Vehl\v-80_misc2.pac","O\Vehl\v-80_podmotlod.pac","O\Vehl\v-80_raketlod.pac","O\Vehl\v-80_rotor.pac","O\Vehl\v-80_rotor2.pac","O\Vehl\v-80_side1lod.paa","O\Vehl\v-80_side2lod.paa","O\Vehl\v-80_test4a.pac","O\Vehl\v-80_test4b2.pac","O\Vehl\v-80_testbott4a.pac","O\Vehl\v-80_testbott4b.pac","O\Vehl\v-80_testtop4a.pac","O\Vehl\v-80_testtop4b.pac","O\Vehl\v-80_testwing.pac","O\Vehl\v-80_undergun.pac","O\Vehl\v-80_unguided.pac","O\Vehl\v-80_wiretoplod.paa","data\snk3.pac","data\hip_s1.pac","data\hip_s1_lod.paa","data\hip_s1_nolod.pac","data\hip_s1b.pac","data\hip_s1b_lod.paa","data\hip_s1b_nolod.pac","data\hip_s1comp.pac","data\hip_s2.pac","data\hip_spod1.pac","data\hip_spod1_comp.pac","data\hip_spod2.pac","data\hip_top.pac","data\hip_top_comp.pac","data\hip_top_okno.pac","data\hip_top2.pac","data\hip_vreteno_kratke.pac","data\hip_vrt_v.paa","data\hip_zavesnik_f.pac","data\hip_zavesnik_roury_s.pac","data\hip_zavesnik_t.pac","data\hipspodocas.pac","data\hind_front_new.pac","data\hind_raketomet2.pac","data\hind_reketm_zadek.paa","data\hind_reketm2_usti.paa","data\mi24_kridilko.pac","data\mi24_kridlo_m.pac","data\mi24_kridlo_v.pac","data\mi24_nosic.pac","data\mi24_rotor.pac","data\mi24_side1.pac","data\mi24_side2.pac","data\mi24_side3.pac","data\mi24_spodek.pac","data\mi24_spodek_predek.pac","data\mi24_spodek_zadek.pac","data\mi24_vrsek.pac","oh58\kiowa_lyz_f1.paa","oh58\kiowa_lyzsid.paa","oh58\kiowa_nose.pac","oh58\kiowa_nosice.paa","oh58\kiowa_sidetga.paa","oh58\kiowa_top.pac","oh58\kiowa_v_tail.pac","oh58\kiowa_vrtule.pac","oh58\kiowa-koule.pac","oh58\kiowa-koulet.pac","oh58\kiowa-top.pac","oh58\kiowa-winglets.pac","oh58\oh58_sid1.pac","oh58\oh58_sid2.pac","data\scud_raketa.pac","data\scud_raketa1.pac","data\scud_raketa2.pac","su25\su_kridlo1.pac","su25\su_kridlo2.pac","su25\su_kridlokon.pac","su25\su_kridlospod.pac","su25\su25_ch-29t.pac","su25\su25_detaily.pac","su25\su25_motor1.pac","su25\su25_raketomet.pac","su25\su25_sop.pac","su25\su25_spodek.pac","su25\su25_strana1.pac","su25\su25_strana2.pac","su25\su25_strana3.pac","su25\su25_vop.pac","su25\su25_vopspod.pac","data\uh60_cumak.pac","data\uh60_cumak_lod.pac","data\uh60_kridlo2.pac","data\uh60_list_vrtule.pac","data\uh60_nadrz.pac","data\uh60_bottom_new.pac","data\uh60_noha2.pac","data\uh60_nosic_side.pac","data\uh60_ocas.pac","data\uh60_ocas_kridlo.pac","data\uh60_skla1.paa","data\uh60_stred.pac","data\uh60_top_new1.pac","data\uh60_top_new2.pac","data\uh60-motor.pac","data\raketa_kridlo.pac","data\raketa_sidetop.pac","data\raketa_tryska.pac","data\raketa_valecek1.pac","data\raketa_valecek1_fron.pac","data\raketa_valecek2.pac","data\raketomet.pac","data\vrthind_m.paa","data\vrtule_uh_m.pac","data\vrtule_uh_v.paa","data\vrtule_velka.paa"};
		material="#CSLA2_MetalAir";
		};

	class CSLA2_MetalArmor
		{
		textures[]={"data\bmp_ambulance_back.pac","data\bmp_ambulance_sideca.pac","data\bmp_ambulance_top.pac","data\bmp_anm.01.pac","data\bmp_anm.02.pac","data\bmp_anm.03.pac","data\bmp_anm.04.pac","data\bmp_anm.05.pac","data\bmp_back.pac","data\bmp_side.pac","data\bmp_side_hi.pac","data\bmp_top.pac","data\bmp_vez_back.pac","data\bmp_vez_top.pac","BMP2\2a42kanon-final.paa","BMP2\at6-launcher.pac","BMP2\bmp2_top.pac","BMP2\bmp2_vez_back.pac","BMP2\bmp2_vez_frnt.pac","BMP2\rocket-backfront.pac","BMP2\rocket-side.pac","BMP2\smoke-prefinal.pac","brmd\brmd_detaily.pac","brmd\brmd_haubna.pac","brmd\brmd_krabiceammo.pac","brmd\brmd_predek1.pac","brmd\brmd_predek2.pac","brmd\brmd_strana1.pac","brmd\brmd_strana2.pac","brmd\brmdsvetla.pac","brmd\brmdvrch1.pac","brmd\brmdvrch2.pac","brmd\brmdzadek.pac","data\m113front.pac","data\m113krbbok.pac","data\m113krbfrt.pac","data\m113plat_uni.pac","data\m113sanita-side_lod.pac","data\m113sanita-top.pac","data\m113top.pac","data\m133_newback.pac","data\m133_newfront.pac","data\m133_newfrontlod.pac","data\m133_newside.pac","data\m133_newsideamb.pac","data\m133_newtop.pac","vulcan\vulcan_1.pac","vulcan\vulcan_2.pac","vulcan\vulcan_3.pac","vulcan\vulcan_4.pac","vulcan\vulcan_hlavne.pac","vulcan\vulcan_kanon.pac","vulcan\vulcan_kolas.pac","vulcan\vulcan_ku4l.pac","vulcan\vulcan_kukr.paa","vulcan\vulcan_kukr.pac","vulcan\vulcan_kul2.pac","vulcan\vulcan_kul3.pac","vulcan\vulcan_newtop.pac","vulcan\vulcan_side.pac","vulcan\vulcan1.pac","vulcan\vulcan2.pac","vulcan\vulcan3.pac","data\abrams_roury_frt.pac","data\abrams_roury_side.pac","data\abrams_svetlo.paa","data\abrams_svetlo_b.paa","data\m1a1_bocek.pac","data\m1a1_frnt_bck_lod.pac","data\m1a1_hlaven.pac","data\m1a1_main_back.pac","data\m1a1_main_front.pac","data\m1a1_main_side.pac","data\m1a1_main_top.pac","data\m1a1_vez_back.pac","data\m1a1_vez_front.pac","data\m1a1_vez_hatch.pac","data\m1a1_vez_side.pac","data\m1a1_vez_top.pac","data\m1a1_vymetnice.pac","data\tank_m_02_frt.pac","data\tank_m_02_kanon.pac","data\tank_m_02_kanon_2.pac","data\tank_m_02_spod.pac","data\tank_m_02_top.pac","data\tank_m_02_vez_frt.pac","data\tank_m_02_vez_side.pac","data\tank_m_02_vez_top.pac","m2a2\m2a2_back.pac","m2a2\m2a2_bk.pac","m2a2\m2a2_dn.pac","m2a2\m2a2_down.pac","m2a2\m2a2_sid1a.pac","m2a2\m2a2_sid1b.pac","m2a2\m2a2_sid2a.pac","m2a2\m2a2_sid2b.pac","m2a2\m2a2_sida.pac","m2a2\m2a2_sidb.pac","m2a2\m2a2_up.pac","m2a2\m2a2_upa.pac","m2a2\m2a2_upb.pac","m2a2\m2a2_upvez.pac","m2a2\m2a2_upveza.pac","m2a2\m2a2_upvezb.pac","m2a2\m2a2_upvezc.pac","m2a2\m2a2_upvezd.pac","data\m60_poklop_driver.pac","data\m60_sidepas.pac","data\m60_t_back.pac","data\m60_t_front.pac","data\m60_t_side.pac","data\m60_t_top.pac","data\m60_tc_front.pac","data\m60_tc_side.pac","data\m60_zadni_rantl.paa","data\m60hullback.pac","data\m60hullback2.pac","data\m60hullfront.pac","data\m60hullfront2.pac","data\m60hulltop.pac","data\t55_blbosti.pac","data\t55_bok.pac","data\t55_detaily.pac","data\t55_hlaven.pac","data\t55_infra.pac","data\t55_poklop.paa","data\t55_predek.pac","data\t55_spodek.pac","data\t55_sum.pac","data\t55_top.pac","data\t55_vez_side.pac","data\t55_zadek.pac","data\t55s_side.pac","data\t55vez_top.pac","data\t72_back.pac","data\t72_com_strop.paa","data\t72_dri_poklop.paa","data\t72_front.pac","data\t72_gun_delo2.paa","data\t-72_gun_delo3.paa","data\t72_hlaven_s.pac","data\t72_pixla_side.pac","data\t72_sum.pac","data\t72_top.pac","data\t72_vez_back.pac","data\t72_vez_front.pac","data\t72_vez_roura.pac","data\t72_vez_side.pac","data\t72_vez_top.pac","data\t72pasb.pac","data\tank_03_kanon_frt.pac","data\tank_04_bednyuvalce_.pac","data\tank_04_detailkanon.pac","data\tank_04_detailkanon2.pac","data\tank_04_frt.pac","data\tank_04_krabic_back.pac","data\tank_04_krabic_sidet.pac","data\tank_04_lauf_frt.pac","data\tank_04_lauf_top.pac","data\tank_04_platyzveze_s.pac","data\tank_04_platyzvozu_t.pac","data\tank_04_side.pac","data\tank_04_spod.pac","data\tank_04_spod_spol.pac","data\tank_04_sud_norm.pac","data\tank_04_sud_side.paa","data\tank_04_top.pac","data\tank_04_v_lec_norm.pac","data\tank_04_v_lec_side.paa","data\tank_04_vez_bck.pac","data\tank_04_vez_frt.pac","data\tank_04_vez_side.pac","data\tank_04_vez_top.pac","data\tank4_passide.pac","data\tnk04topslo.pac","data\zsu_back2.pac","data\zsu_back2_lod.pac","data\zsu_front2.pac","data\zsu_front2_lod.pac","data\zsu_pasy_side2.pac","data\zsu_plech.pac","data\zsu_podlaha.paa","data\zsu_radar_side.pac","data\zsu_radar_top2.pac","data\zsu_side2.pac","data\zsu_spod.pac","data\zsu_spod_lod.pac","data\zsu_top.pac","data\zsu_vez_top.pac"};
		material="#CSLA2_MetalArmor";
		};

	class CSLA2_MetalCar
		{
		textures[]={""};
		material="#CSLA2_MetalCar";
		};

	};
class CfgMaterials {

	class Water
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.4,0.4,0.45,0};
		specularPower=6;
		emmisive[]={0,0,0,0};
		};

	class Terrain
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.03,0.03,0.03,0};
		specularPower=3;
		emmisive[]={0,0,0,0};
		};

	class SpecularGlass
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.8,0.8,0.8,0};
		specularPower=5;
		emmisive[]={0,0,0,0};
		};

	class Metal
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.2,0.2,0.2,0};
		specularPower=6;
		emmisive[]={0,0,0,0};
		};

	class RifleMetal0
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.3,0.3,0.3,1};
		specularPower=900;
		emmisive[]={0,0,0,0};
		};

	class RifleMetal
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.3,0.3,0.3,1};
		specularPower=900;
		emmisive[]={0,0,0,0};
		};

	class RifleMetal2
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.36,0.36,0.36,0};
		specularPower=10;
		emmisive[]={0,0,0,0};
		};

	class RifleMetallow
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.12,0.12,0.15,0};
		specularPower=900;
		emmisive[]={0,0,0,0};
		};

	class RifleMetalG36
		{
		ambient[]={0.95,0.95,0.95,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.22,0.22,0.23,1};
		specularPower=10;
		emmisive[]={0,0,0,0};
		};

	class RifleMetalAK74P
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.1,0.1,0.1,1};
		specularPower=100;
		emmisive[]={0,0,0,0};
		};

	class AirMetallow
		{
		ambient[]={0.92,0.92,0.92,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.2,0.2,0.2,1};
		specularPower=900;
		emmisive[]={0,0,0,0};
		};

	class MiscMetal
		{
		ambient[]={0.9,0.9,0.9,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.5,0.5,0.5,1};
		specularPower=400;
		emmisive[]={0,0,0,0};
		};

	class CessnaMetal
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.5,0.5,0.75,0};
		specularPower=15;
		emmisive[]={0,0,0,0};
		};

	class CSLA2_MetalAir
		{
		ambient[]={0.7,0.7,0.7,0.9};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.4,0.4,0.5,0};
		specularPower=6;
		emmisive[]={0,0,0,0};
		};

	class CSLA2_MetalArmor
		{
		ambient[]={0.75,0.75,0.7,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.26,0.26,0.3,0};
		specularPower=5;
		emmisive[]={0,0,0,0};
		};

	class CSLA2_MetalCar
		{
		ambient[]={1,1,1,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.3,0.3,0.4,0};
		specularPower=5;
		emmisive[]={0,0,0,0};
		};

	class ETONmetalVeh
		{
		ambient[]={0.9,0.9,0.9,1};
		diffuse[]={1,1,1,1};
		forcedDiffuse[]={0,0,0,0};
		specular[]={0.5,0.5,0.5,1};
		specularPower=400;
		emmisive[]={0,0,0,0};
		};

	};
